/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module usb_bit_destuffer(clk_144, rst_144_n, enable, data_strobe, data_bit, bit_valid, out_bit, stuff_err);
  input clk_144;
  wire clk_144;
  input rst_144_n;
  wire rst_144_n;
  input enable;
  wire enable;
  input data_strobe;
  wire data_strobe;
  input data_bit;
  wire data_bit;
  output bit_valid;
  wire bit_valid;
  output out_bit;
  wire out_bit;
  output stuff_err;
  wire stuff_err;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [2:0] ones_run;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _16_ (
    .A1(ones_run[1]),
    .A2(ones_run[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _17_ (
    .A1(ones_run[0]),
    .A2(_06_),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _18_ (
    .I(data_strobe),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _19_ (
    .A1(enable),
    .A2(_07_),
    .B(_08_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_1 _20_ (
    .A1(data_strobe),
    .A2(enable),
    .A3(data_bit),
    .A4(_07_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _21_ (
    .A1(enable),
    .A2(data_bit),
    .A3(_06_),
    .Z(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _22_ (
    .A1(_08_),
    .A2(enable),
    .B(_09_),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _23_ (
    .I(ones_run[0]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _24_ (
    .A1(_08_),
    .A2(enable),
    .B(_11_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _25_ (
    .A1(ones_run[1]),
    .A2(_12_),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _26_ (
    .A1(_10_),
    .A2(_13_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _27_ (
    .I0(out_bit),
    .I1(data_bit),
    .S(_00_),
    .Z(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _28_ (
    .A1(ones_run[1]),
    .A2(_12_),
    .B(ones_run[2]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _29_ (
    .A1(_10_),
    .A2(_14_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _30_ (
    .A1(data_strobe),
    .A2(_09_),
    .B(ones_run[0]),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _31_ (
    .A1(_12_),
    .A2(_15_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _32_ (
    .CLK(clk_144),
    .D(_03_),
    .Q(out_bit),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _33_ (
    .CLK(clk_144),
    .D(_05_),
    .Q(ones_run[0]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _34_ (
    .CLK(clk_144),
    .D(_02_),
    .Q(ones_run[1]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _35_ (
    .CLK(clk_144),
    .D(_04_),
    .Q(ones_run[2]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _36_ (
    .CLK(clk_144),
    .D(_00_),
    .Q(bit_valid),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _37_ (
    .CLK(clk_144),
    .D(_01_),
    .Q(stuff_err),
    .RN(rst_144_n)
  );
endmodule

module usb_bit_stuffer(clk, rst_n, bit_stb, bypass, sof, bit_in, bit_out, consume, stuff_pending_after);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input bit_stb;
  wire bit_stb;
  input bypass;
  wire bypass;
  input sof;
  wire sof;
  input bit_in;
  wire bit_in;
  output bit_out;
  wire bit_out;
  output consume;
  wire consume;
  output stuff_pending_after;
  wire stuff_pending_after;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] run;
  gf180mcu_fd_sc_mcu9t5v0__inv_3 _14_ (
    .I(run[0]),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_4 _15_ (
    .A1(bypass),
    .A2(sof),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_4 _16_ (
    .A1(run[1]),
    .A2(_03_),
    .A3(run[2]),
    .A4(_04_),
    .ZN(consume)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _17_ (
    .A1(bit_in),
    .A2(consume),
    .Z(bit_out)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _18_ (
    .A1(run[2]),
    .A2(bit_in),
    .A3(_04_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _19_ (
    .A1(run[1]),
    .A2(_03_),
    .A3(_05_),
    .ZN(stuff_pending_after)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _20_ (
    .A1(_03_),
    .A2(consume),
    .B(sof),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _21_ (
    .I(bypass),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _22_ (
    .A1(_07_),
    .A2(bit_in),
    .A3(bit_stb),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai22_1 _23_ (
    .A1(_03_),
    .A2(bit_stb),
    .B1(_06_),
    .B2(_08_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _24_ (
    .A1(bit_in),
    .A2(_04_),
    .A3(consume),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _25_ (
    .A1(run[0]),
    .A2(bit_stb),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_1 _26_ (
    .A1(run[1]),
    .A2(_10_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _27_ (
    .A1(bit_stb),
    .A2(_09_),
    .B(_11_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _28_ (
    .A1(run[1]),
    .A2(run[0]),
    .A3(bit_stb),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _29_ (
    .A1(run[2]),
    .A2(_12_),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _30_ (
    .A1(bit_stb),
    .A2(_09_),
    .B(_13_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _31_ (
    .CLK(clk),
    .D(_00_),
    .Q(run[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _32_ (
    .CLK(clk),
    .D(_01_),
    .Q(run[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _33_ (
    .CLK(clk),
    .D(_02_),
    .Q(run[2]),
    .RN(rst_n)
  );
endmodule

module usb_eop_detector(clk, rst_n, line_state, eop, bus_reset);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [1:0] line_state;
  wire [1:0] line_state;
  output eop;
  wire eop;
  output bus_reset;
  wire bus_reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [5:0] se0_count;
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _27_ (
    .A1(line_state[0]),
    .A2(line_state[1]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _28_ (
    .A1(rst_n),
    .A2(_08_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_4 _29_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _30_ (
    .I(se0_count[0]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _31_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(se0_count[1]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _32_ (
    .A1(_10_),
    .A2(_12_),
    .B(bus_reset),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _33_ (
    .A1(_09_),
    .A2(_13_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _34_ (
    .I(se0_count[1]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _35_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(_14_),
    .A4(_10_),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _36_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _37_ (
    .A1(_09_),
    .A2(_16_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _38_ (
    .I(se0_count[5]),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _39_ (
    .A1(_17_),
    .A2(se0_count[0]),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _40_ (
    .A1(_14_),
    .A2(_18_),
    .B(_15_),
    .C(_09_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _41_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .B(_18_),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _42_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _43_ (
    .A1(_17_),
    .A2(_20_),
    .B(se0_count[0]),
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _44_ (
    .A1(_09_),
    .A2(_19_),
    .A3(_21_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _45_ (
    .I(se0_count[4]),
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _46_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _47_ (
    .A1(_22_),
    .A2(_23_),
    .B(_09_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _48_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .Z(_24_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _49_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .B(se0_count[3]),
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _50_ (
    .A1(_09_),
    .A2(_24_),
    .A3(_25_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _51_ (
    .A1(_17_),
    .A2(_09_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _52_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .A4(_09_),
    .ZN(_26_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _53_ (
    .A1(_12_),
    .A2(_26_),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _54_ (
    .CLK(clk),
    .D(_00_),
    .Q(bus_reset)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _55_ (
    .CLK(clk),
    .D(_07_),
    .Q(eop)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _56_ (
    .CLK(clk),
    .D(_03_),
    .Q(se0_count[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _57_ (
    .CLK(clk),
    .D(_02_),
    .Q(se0_count[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _58_ (
    .CLK(clk),
    .D(_01_),
    .Q(se0_count[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _59_ (
    .CLK(clk),
    .D(_05_),
    .Q(se0_count[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _60_ (
    .CLK(clk),
    .D(_04_),
    .Q(se0_count[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _61_ (
    .CLK(clk),
    .D(_06_),
    .Q(se0_count[5])
  );
endmodule

module usb_line_state_decode(clk, rst_n, rxdp, rxdm, line_state);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  output [1:0] line_state;
  wire [1:0] line_state;
  wire _0_;
  wire _1_;
  wire _2_;
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _3_ (
    .I(rxdp),
    .ZN(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _4_ (
    .A1(_2_),
    .A2(rst_n),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _5_ (
    .A1(rst_n),
    .A2(rxdm),
    .Z(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(line_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _7_ (
    .CLK(clk),
    .D(_1_),
    .Q(line_state[1])
  );
endmodule

module usb_nrzi_decoder(clk_144, rst_144_n, bit_strobe, bit_level, bit_is_jk, data_strobe, data_bit);
  input clk_144;
  wire clk_144;
  input rst_144_n;
  wire rst_144_n;
  input bit_strobe;
  wire bit_strobe;
  input bit_level;
  wire bit_level;
  input bit_is_jk;
  wire bit_is_jk;
  output data_strobe;
  wire data_strobe;
  output data_bit;
  wire data_bit;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire prev_level;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _05_ (
    .A1(bit_strobe),
    .A2(bit_is_jk),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _06_ (
    .I(_04_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _07_ (
    .I0(bit_level),
    .I1(prev_level),
    .S(_04_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _08_ (
    .A1(bit_level),
    .A2(prev_level),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _09_ (
    .I0(_03_),
    .I1(data_bit),
    .S(_04_),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffsnq_1 _10_ (
    .CLK(clk_144),
    .D(_01_),
    .Q(prev_level),
    .SETN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _11_ (
    .CLK(clk_144),
    .D(_02_),
    .Q(data_bit),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _12_ (
    .CLK(clk_144),
    .D(_00_),
    .Q(data_strobe),
    .RN(rst_144_n)
  );
endmodule

module usb_nrzi_encoder(clk, rst_n, bit_stb, bypass, sof, bit_in, level_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input bit_stb;
  wire bit_stb;
  input bypass;
  wire bypass;
  input sof;
  wire sof;
  input bit_in;
  wire bit_in;
  output level_out;
  wire level_out;
  wire _0_;
  wire _1_;
  wire _2_;
  gf180mcu_fd_sc_mcu9t5v0__nor3_4 _3_ (
    .A1(bypass),
    .A2(level_out),
    .A3(sof),
    .ZN(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _4_ (
    .A1(bit_in),
    .A2(_1_),
    .Z(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _5_ (
    .I0(level_out),
    .I1(_2_),
    .S(bit_stb),
    .Z(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffsnq_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(level_out),
    .SETN(rst_n)
  );
endmodule

module usb_sync_detector(clk, rst_n, enable, data_valid, data_bit, sync_valid, sync_next);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input enable;
  wire enable;
  input data_valid;
  wire data_valid;
  input data_bit;
  wire data_bit;
  output sync_valid;
  wire sync_valid;
  output sync_next;
  wire sync_next;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [3:0] match;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _16_ (
    .I(enable),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _17_ (
    .A1(match[0]),
    .A2(match[1]),
    .A3(match[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _18_ (
    .A1(data_valid),
    .A2(data_bit),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _19_ (
    .A1(match[3]),
    .A2(_05_),
    .A3(_06_),
    .A4(_07_),
    .ZN(sync_next)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _20_ (
    .I(match[3]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _21_ (
    .A1(enable),
    .A2(rst_n),
    .A3(_07_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _22_ (
    .A1(match[0]),
    .A2(data_valid),
    .A3(match[1]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _23_ (
    .A1(match[2]),
    .A2(_10_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _24_ (
    .A1(_08_),
    .A2(_09_),
    .A3(_11_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _25_ (
    .A1(match[2]),
    .A2(_10_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _26_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _27_ (
    .A1(match[0]),
    .A2(data_valid),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _28_ (
    .A1(match[1]),
    .A2(_13_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _29_ (
    .A1(_09_),
    .A2(_10_),
    .A3(_14_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _30_ (
    .A1(match[0]),
    .A2(data_valid),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _31_ (
    .A1(_06_),
    .A2(_13_),
    .B(_15_),
    .C(_09_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _32_ (
    .A1(rst_n),
    .A2(sync_next),
    .Z(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(sync_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _34_ (
    .CLK(clk),
    .D(_03_),
    .Q(match[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _35_ (
    .CLK(clk),
    .D(_02_),
    .Q(match[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _36_ (
    .CLK(clk),
    .D(_01_),
    .Q(match[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _37_ (
    .CLK(clk),
    .D(_00_),
    .Q(match[3])
  );
endmodule

module usb_utmi_phy(clk, rst_n, TxValid, TxReady, DataOut, RxValid, RxActive, RxError, DataIn, LineState, OpMode, TermSelect, XcvrSelect, SuspendM, Reset, txdp, txdm, rxdp, rxdm);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input TxValid;
  wire TxValid;
  output TxReady;
  wire TxReady;
  input [7:0] DataOut;
  wire [7:0] DataOut;
  output RxValid;
  wire RxValid;
  output RxActive;
  wire RxActive;
  output RxError;
  wire RxError;
  output [7:0] DataIn;
  wire [7:0] DataIn;
  output [1:0] LineState;
  wire [1:0] LineState;
  input [1:0] OpMode;
  wire [1:0] OpMode;
  input TermSelect;
  wire TermSelect;
  input XcvrSelect;
  wire XcvrSelect;
  input SuspendM;
  wire SuspendM;
  input Reset;
  wire Reset;
  output txdp;
  wire txdp;
  output txdm;
  wire txdm;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire bus_reset;
  wire [2:0] byte_idx;
  wire [7:0] byte_reg;
  wire dec_bit_level;
  wire dec_bit_strobe;
  wire dec_data_bit;
  wire dec_data_strobe;
  wire entering_sync;
  wire eop_pulse;
  wire first_byte;
  wire int_rst_n;
  wire [1:0] line_state;
  wire nrzi_level;
  wire raw_mode;
  wire rx_assembly_en;
  wire rx_bit_valid;
  wire [2:0] rx_bitcnt;
  wire rx_out_bit;
  wire rx_receiving;
  wire [7:0] rx_shift;
  wire [7:0] rx_shift_next;
  wire rx_stuff_err;
  wire stuff_bit_out;
  wire stuff_consume;
  wire stuff_pending_after;
  wire [2:0] sync_idx;
  wire sync_next;
  wire tx_body_active;
  wire [7:0] tx_state;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _148_ (
    .I(rx_receiving),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _149_ (
    .I(Reset),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _150_ (
    .A1(rst_n),
    .A2(_051_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _151_ (
    .I(_052_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_2 _152_ (
    .I(_053_),
    .Z(int_rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_4 _153_ (
    .I(tx_state[2]),
    .Z(_054_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_4 _154_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(byte_idx[2]),
    .A4(_054_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _155_ (
    .A1(TxValid),
    .A2(_055_),
    .Z(_056_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _156_ (
    .A1(stuff_consume),
    .A2(int_rst_n),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _157_ (
    .A1(tx_state[6]),
    .A2(int_rst_n),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai31_1 _158_ (
    .A1(stuff_pending_after),
    .A2(_056_),
    .A3(_057_),
    .B(_058_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _159_ (
    .A1(tx_state[1]),
    .A2(int_rst_n),
    .Z(_001_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _160_ (
    .I(tx_state[0]),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _161_ (
    .I(tx_state[7]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _162_ (
    .A1(TxValid),
    .A2(_059_),
    .B(_060_),
    .C(int_rst_n),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _163_ (
    .A1(TxValid),
    .A2(tx_state[0]),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _164_ (
    .I(_061_),
    .ZN(entering_sync)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _165_ (
    .I(tx_state[4]),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _166_ (
    .A1(sync_idx[0]),
    .A2(sync_idx[2]),
    .A3(sync_idx[1]),
    .Z(_063_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _167_ (
    .A1(_062_),
    .A2(_063_),
    .Z(_064_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_1 _168_ (
    .I(_052_),
    .Z(_065_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _169_ (
    .A1(_061_),
    .A2(_064_),
    .B(_065_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _170_ (
    .I(stuff_pending_after),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _171_ (
    .A1(_066_),
    .A2(_056_),
    .A3(_057_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _172_ (
    .I(line_state[0]),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _173_ (
    .A1(_067_),
    .A2(line_state[1]),
    .ZN(dec_bit_level)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_1 _174_ (
    .A1(line_state[0]),
    .A2(line_state[1]),
    .Z(dec_bit_strobe)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _175_ (
    .A1(_054_),
    .A2(tx_state[6]),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _176_ (
    .I(_068_),
    .ZN(tx_body_active)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _177_ (
    .A1(_054_),
    .A2(tx_state[6]),
    .A3(tx_state[4]),
    .A4(tx_state[1]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _178_ (
    .A1(tx_state[5]),
    .A2(tx_state[3]),
    .Z(_070_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _179_ (
    .A1(tx_state[7]),
    .A2(nrzi_level),
    .A3(_069_),
    .A4(_070_),
    .ZN(txdm)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _180_ (
    .A1(tx_state[7]),
    .A2(nrzi_level),
    .A3(_069_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _181_ (
    .A1(_071_),
    .A2(_070_),
    .ZN(txdp)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _182_ (
    .A1(tx_state[5]),
    .A2(int_rst_n),
    .Z(_000_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _183_ (
    .A1(tx_state[3]),
    .A2(int_rst_n),
    .Z(_003_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _184_ (
    .I(stuff_consume),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _185_ (
    .A1(_072_),
    .A2(_055_),
    .B(_059_),
    .ZN(TxReady)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _186_ (
    .A1(tx_state[4]),
    .A2(_063_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_4 _187_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(byte_idx[2]),
    .A4(stuff_consume),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _188_ (
    .A1(TxValid),
    .A2(_074_),
    .B(_054_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _189_ (
    .A1(_073_),
    .A2(_075_),
    .B(_065_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _190_ (
    .A1(tx_state[4]),
    .A2(entering_sync),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _191_ (
    .I0(_063_),
    .I1(stuff_bit_out),
    .S(_076_),
    .Z(_013_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _192_ (
    .I(OpMode[1]),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _193_ (
    .A1(_077_),
    .A2(OpMode[0]),
    .ZN(raw_mode)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _194_ (
    .A1(_077_),
    .A2(OpMode[0]),
    .A3(_068_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _195_ (
    .A1(_068_),
    .A2(_076_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux4_1 _196_ (
    .I0(byte_reg[2]),
    .I1(byte_reg[3]),
    .I2(byte_reg[6]),
    .I3(byte_reg[7]),
    .S0(byte_idx[0]),
    .S1(byte_idx[2]),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _197_ (
    .A1(byte_idx[1]),
    .A2(_078_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _198_ (
    .I(byte_idx[1]),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux4_1 _199_ (
    .I0(byte_reg[0]),
    .I1(byte_reg[1]),
    .I2(byte_reg[4]),
    .I3(byte_reg[5]),
    .S0(byte_idx[0]),
    .S1(byte_idx[2]),
    .Z(_081_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _200_ (
    .A1(_080_),
    .A2(_081_),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _201_ (
    .A1(_079_),
    .A2(_082_),
    .B(tx_state[6]),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _202_ (
    .A1(first_byte),
    .A2(_054_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _203_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(byte_idx[2]),
    .A4(_083_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _204_ (
    .A1(rx_bit_valid),
    .A2(rx_assembly_en),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _205_ (
    .A1(rx_shift[5]),
    .A2(_084_),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _206_ (
    .A1(rx_bit_valid),
    .A2(rx_assembly_en),
    .Z(_086_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_8 _207_ (
    .I(_086_),
    .Z(_087_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _208_ (
    .A1(rx_shift[6]),
    .A2(_087_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _209_ (
    .A1(rx_receiving),
    .A2(_053_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _210_ (
    .A1(_085_),
    .A2(_088_),
    .B(_089_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _211_ (
    .I(DataOut[6]),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _212_ (
    .A1(tx_state[2]),
    .A2(TxValid),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi22_4 _213_ (
    .A1(_054_),
    .A2(_074_),
    .B1(_091_),
    .B2(_061_),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_4 _214_ (
    .I(_092_),
    .Z(_093_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _215_ (
    .A1(byte_reg[6]),
    .A2(_092_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _216_ (
    .A1(_090_),
    .A2(_093_),
    .B(_094_),
    .C(_065_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_4 _217_ (
    .A1(rx_bitcnt[1]),
    .A2(rx_bitcnt[0]),
    .A3(_087_),
    .Z(_095_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_4 _218_ (
    .A1(rx_receiving),
    .A2(rx_bitcnt[2]),
    .A3(_053_),
    .A4(_095_),
    .Z(_096_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkbuf_12 _219_ (
    .I(_096_),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _220_ (
    .I0(DataIn[7]),
    .I1(rx_out_bit),
    .S(_041_),
    .Z(_016_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _221_ (
    .I(_089_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _222_ (
    .I(DataOut[5]),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _223_ (
    .A1(byte_reg[5]),
    .A2(_092_),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _224_ (
    .A1(_097_),
    .A2(_093_),
    .B(_098_),
    .C(_065_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _225_ (
    .I(DataOut[4]),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _226_ (
    .A1(byte_reg[4]),
    .A2(_092_),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _227_ (
    .A1(_099_),
    .A2(_093_),
    .B(_100_),
    .C(_065_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _228_ (
    .I(DataOut[3]),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _229_ (
    .A1(byte_reg[3]),
    .A2(_093_),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _230_ (
    .A1(_101_),
    .A2(_093_),
    .B(_102_),
    .C(_065_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _231_ (
    .A1(rx_shift[7]),
    .A2(_084_),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _232_ (
    .A1(rx_out_bit),
    .A2(_087_),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _233_ (
    .A1(_103_),
    .A2(_104_),
    .B(_089_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _234_ (
    .I(DataOut[2]),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _235_ (
    .A1(byte_reg[2]),
    .A2(_092_),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _236_ (
    .A1(_105_),
    .A2(_093_),
    .B(_106_),
    .C(_052_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _237_ (
    .I(DataOut[1]),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _238_ (
    .A1(byte_reg[1]),
    .A2(_092_),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _239_ (
    .A1(_107_),
    .A2(_093_),
    .B(_108_),
    .C(_065_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _240_ (
    .I(DataOut[0]),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _241_ (
    .A1(byte_reg[0]),
    .A2(_092_),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _242_ (
    .A1(_109_),
    .A2(_093_),
    .B(_110_),
    .C(_065_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _243_ (
    .A1(rx_shift[4]),
    .A2(_084_),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _244_ (
    .A1(rx_shift[5]),
    .A2(_087_),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _245_ (
    .A1(_111_),
    .A2(_112_),
    .B(_089_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _246_ (
    .A1(rx_shift[3]),
    .A2(_084_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _247_ (
    .A1(rx_shift[4]),
    .A2(_087_),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _248_ (
    .A1(_113_),
    .A2(_114_),
    .B(_089_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _249_ (
    .A1(rx_shift[2]),
    .A2(_084_),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _250_ (
    .A1(rx_shift[3]),
    .A2(_087_),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _251_ (
    .A1(_115_),
    .A2(_116_),
    .B(_089_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _252_ (
    .A1(rx_shift[1]),
    .A2(_084_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _253_ (
    .A1(rx_shift[2]),
    .A2(_087_),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _254_ (
    .A1(_117_),
    .A2(_118_),
    .B(_089_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _255_ (
    .I0(tx_state[4]),
    .I1(TxValid),
    .S(tx_state[0]),
    .Z(_119_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _256_ (
    .A1(sync_idx[0]),
    .A2(_119_),
    .Z(_120_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _257_ (
    .A1(sync_idx[1]),
    .A2(_120_),
    .Z(_121_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi221_1 _258_ (
    .A1(_062_),
    .A2(entering_sync),
    .B1(_120_),
    .B2(sync_idx[1]),
    .C(_052_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _259_ (
    .A1(_121_),
    .A2(_122_),
    .Z(_029_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _260_ (
    .A1(sync_idx[1]),
    .A2(_120_),
    .B(sync_idx[2]),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _261_ (
    .A1(_064_),
    .A2(_119_),
    .B(_123_),
    .C(_052_),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _262_ (
    .I(first_byte),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai22_1 _263_ (
    .A1(_054_),
    .A2(_061_),
    .B1(_093_),
    .B2(_124_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _264_ (
    .A1(int_rst_n),
    .A2(_125_),
    .Z(_031_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _265_ (
    .A1(sync_idx[0]),
    .A2(_119_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _266_ (
    .A1(tx_state[4]),
    .A2(_120_),
    .B(_126_),
    .C(_052_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_4 _267_ (
    .A1(rx_bitcnt[0]),
    .A2(_087_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _268_ (
    .A1(_089_),
    .A2(_127_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _269_ (
    .I0(DataIn[6]),
    .I1(rx_shift[7]),
    .S(_041_),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _270_ (
    .I0(DataIn[5]),
    .I1(rx_shift[6]),
    .S(_041_),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _271_ (
    .A1(rx_bitcnt[2]),
    .A2(_095_),
    .B(int_rst_n),
    .C(rx_receiving),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _272_ (
    .A1(rx_bitcnt[2]),
    .A2(_095_),
    .B(_128_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _273_ (
    .I0(DataIn[4]),
    .I1(rx_shift[5]),
    .S(_041_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _274_ (
    .I(DataOut[7]),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _275_ (
    .A1(byte_reg[7]),
    .A2(_092_),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _276_ (
    .A1(_129_),
    .A2(_093_),
    .B(_130_),
    .C(_065_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _277_ (
    .I0(DataIn[3]),
    .I1(rx_shift[4]),
    .S(_041_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _278_ (
    .I(byte_idx[2]),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _279_ (
    .I(byte_idx[0]),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _280_ (
    .I0(tx_state[4]),
    .I1(stuff_consume),
    .S(tx_state[2]),
    .Z(_133_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai221_2 _281_ (
    .A1(TxValid),
    .A2(_055_),
    .B1(_063_),
    .B2(_062_),
    .C(_133_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or3_2 _282_ (
    .A1(_132_),
    .A2(_080_),
    .A3(_134_),
    .Z(_135_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _283_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(byte_idx[2]),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _284_ (
    .A1(_054_),
    .A2(_136_),
    .B(_134_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _285_ (
    .A1(_131_),
    .A2(_135_),
    .B(_137_),
    .C(_065_),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _286_ (
    .I0(DataIn[2]),
    .I1(rx_shift[3]),
    .S(_041_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _287_ (
    .I0(DataIn[1]),
    .I1(rx_shift[2]),
    .S(_041_),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _288_ (
    .I0(DataIn[0]),
    .I1(rx_shift[1]),
    .S(_041_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _289_ (
    .A1(rx_stuff_err),
    .A2(_017_),
    .Z(_045_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _290_ (
    .A1(_010_),
    .A2(eop_pulse),
    .A3(bus_reset),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _291_ (
    .A1(sync_next),
    .A2(_138_),
    .B(int_rst_n),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _292_ (
    .I(_139_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _293_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .B(_054_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _294_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .B(_140_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _295_ (
    .A1(_134_),
    .A2(_141_),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _296_ (
    .A1(_080_),
    .A2(_134_),
    .B(_142_),
    .C(_052_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_1 _297_ (
    .A1(_054_),
    .A2(stuff_consume),
    .A3(_056_),
    .A4(_064_),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _298_ (
    .A1(_132_),
    .A2(_134_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _299_ (
    .A1(_132_),
    .A2(_143_),
    .B(_144_),
    .C(_052_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _300_ (
    .A1(rx_bitcnt[0]),
    .A2(_087_),
    .B(rx_bitcnt[1]),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _301_ (
    .A1(_089_),
    .A2(_095_),
    .A3(_145_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _302_ (
    .A1(rx_shift[6]),
    .A2(_084_),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _303_ (
    .A1(rx_shift[7]),
    .A2(_087_),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _304_ (
    .A1(_146_),
    .A2(_147_),
    .B(_089_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _305_ (
    .CLK(clk),
    .D(_024_),
    .Q(byte_reg[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _306_ (
    .CLK(clk),
    .D(_023_),
    .Q(byte_reg[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _307_ (
    .CLK(clk),
    .D(_022_),
    .Q(byte_reg[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _308_ (
    .CLK(clk),
    .D(_020_),
    .Q(byte_reg[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _309_ (
    .CLK(clk),
    .D(_019_),
    .Q(byte_reg[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _310_ (
    .CLK(clk),
    .D(_018_),
    .Q(byte_reg[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _311_ (
    .CLK(clk),
    .D(_015_),
    .Q(byte_reg[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _312_ (
    .CLK(clk),
    .D(_038_),
    .Q(byte_reg[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _313_ (
    .CLK(clk),
    .D(_045_),
    .Q(RxError)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _314_ (
    .CLK(clk),
    .D(_032_),
    .Q(sync_idx[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _315_ (
    .CLK(clk),
    .D(_029_),
    .Q(sync_idx[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _316_ (
    .CLK(clk),
    .D(_030_),
    .Q(sync_idx[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _317_ (
    .CLK(clk),
    .D(_048_),
    .Q(byte_idx[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _318_ (
    .CLK(clk),
    .D(_047_),
    .Q(byte_idx[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _319_ (
    .CLK(clk),
    .D(_040_),
    .Q(byte_idx[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _320_ (
    .CLK(clk),
    .D(_041_),
    .Q(RxValid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _321_ (
    .CLK(clk),
    .D(_044_),
    .Q(DataIn[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _322_ (
    .CLK(clk),
    .D(_043_),
    .Q(DataIn[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _323_ (
    .CLK(clk),
    .D(_042_),
    .Q(DataIn[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _324_ (
    .CLK(clk),
    .D(_039_),
    .Q(DataIn[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _325_ (
    .CLK(clk),
    .D(_037_),
    .Q(DataIn[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _326_ (
    .CLK(clk),
    .D(_035_),
    .Q(DataIn[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _327_ (
    .CLK(clk),
    .D(_034_),
    .Q(DataIn[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _328_ (
    .CLK(clk),
    .D(_016_),
    .Q(DataIn[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _329_ (
    .CLK(clk),
    .D(_017_),
    .Q(rx_assembly_en)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _330_ (
    .CLK(clk),
    .D(_028_),
    .Q(rx_shift[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _331_ (
    .CLK(clk),
    .D(_027_),
    .Q(rx_shift[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _332_ (
    .CLK(clk),
    .D(_026_),
    .Q(rx_shift[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _333_ (
    .CLK(clk),
    .D(_025_),
    .Q(rx_shift[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _334_ (
    .CLK(clk),
    .D(_014_),
    .Q(rx_shift[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _335_ (
    .CLK(clk),
    .D(_050_),
    .Q(rx_shift[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _336_ (
    .CLK(clk),
    .D(_021_),
    .Q(rx_shift[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _337_ (
    .CLK(clk),
    .D(_031_),
    .Q(first_byte)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _338_ (
    .CLK(clk),
    .D(_033_),
    .Q(rx_bitcnt[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _339_ (
    .CLK(clk),
    .D(_049_),
    .Q(rx_bitcnt[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _340_ (
    .CLK(clk),
    .D(_036_),
    .Q(rx_bitcnt[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _341_ (
    .CLK(clk),
    .D(_046_),
    .Q(rx_receiving)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _342_ (
    .CLK(clk),
    .D(_004_),
    .Q(tx_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _343_ (
    .CLK(clk),
    .D(_005_),
    .Q(tx_state[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _344_ (
    .CLK(clk),
    .D(_006_),
    .Q(tx_state[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _345_ (
    .CLK(clk),
    .D(_000_),
    .Q(tx_state[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _346_ (
    .CLK(clk),
    .D(_007_),
    .Q(tx_state[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _347_ (
    .CLK(clk),
    .D(_001_),
    .Q(tx_state[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _348_ (
    .CLK(clk),
    .D(_002_),
    .Q(tx_state[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _349_ (
    .CLK(clk),
    .D(_003_),
    .Q(tx_state[7])
  );
  usb_nrzi_decoder u_decoder (
    .bit_is_jk(dec_bit_strobe),
    .bit_level(dec_bit_level),
    .bit_strobe(dec_bit_strobe),
    .clk_144(clk),
    .data_bit(dec_data_bit),
    .data_strobe(dec_data_strobe),
    .rst_144_n(int_rst_n)
  );
  usb_bit_destuffer u_destuffer (
    .bit_valid(rx_bit_valid),
    .clk_144(clk),
    .data_bit(dec_data_bit),
    .data_strobe(dec_data_strobe),
    .enable(rx_receiving),
    .out_bit(rx_out_bit),
    .rst_144_n(int_rst_n),
    .stuff_err(rx_stuff_err)
  );
  usb_nrzi_encoder u_encoder (
    .bit_in(_013_),
    .bit_stb(_011_),
    .bypass(_009_),
    .clk(clk),
    .level_out(nrzi_level),
    .rst_n(int_rst_n),
    .sof(entering_sync)
  );
  usb_eop_detector u_eop_detector (
    .bus_reset(bus_reset),
    .clk(clk),
    .eop(eop_pulse),
    .line_state(line_state),
    .rst_n(int_rst_n)
  );
  usb_line_state_decode u_line_state (
    .clk(clk),
    .line_state(line_state),
    .rst_n(int_rst_n),
    .rxdm(rxdm),
    .rxdp(rxdp)
  );
  usb_bit_stuffer u_stuffer (
    .bit_in(_012_),
    .bit_out(stuff_bit_out),
    .bit_stb(tx_body_active),
    .bypass(raw_mode),
    .clk(clk),
    .consume(stuff_consume),
    .rst_n(int_rst_n),
    .sof(_008_),
    .stuff_pending_after(stuff_pending_after)
  );
  usb_sync_detector u_sync_detector (
    .clk(clk),
    .data_bit(dec_data_bit),
    .data_valid(dec_data_strobe),
    .enable(_010_),
    .rst_n(int_rst_n),
    .sync_next(sync_next)
  );
  assign rx_shift_next = { rx_out_bit, rx_shift[7:1] };
  assign LineState = line_state;
  assign RxActive = rx_receiving;
endmodule
