#!/usr/bin/env python3
"""Export ngspice netlists from the xschem sources in ``design/``.

    python3 design/netlist.py            # regenerate design/netlist/*.spice
    python3 design/netlist.py --check    # verify committed netlists are current
    python3 design/netlist.py --cell differential_driver

Every ``design/*.sch`` cell is netlisted **as a ``.subckt``** into
``design/netlist/<cell>.spice`` via a real, headless `xschem -x -q -n` run
(no X11/DISPLAY required -- confirmed working in this repo's environment).
There is no designated top-level/hierarchy cell yet (issue #30's two cells,
the differential driver and the D+ pull-up, are each flat leaf blocks with
no sub-instances of one another or of anything else in ``design/``) -- so,
unlike the fleet's hierarchy-carrying siblings (e.g. gf180-temp-por's own
``design/netlist.py``), this script has no ``TOP_CELL`` concept and no
cross-cell pinout invariants to check. A future issue that adds a PHY-level
wrapper instantiating these cells is expected to extend this script with
that machinery, not reinvent it.

The export is deterministic: absolute paths that xschem records in
``sch_path`` comments are rewritten repo-relative, so the same sources
produce byte-identical netlists on any machine. ``--check`` re-runs the
export into a temporary directory and diffs it against what is committed;
it fails if the committed netlists are stale or the export is not
reproducible.

PDK discovery is delegated to ``sim/harness/pdk.py`` so the repo has exactly
one implementation of "where is gf180mcu". Ported from gf180-temp-por's
``design/netlist.py`` (CLAUDE.md's harness-bootstrap instruction), simplified
for this repo's flat (non-hierarchical) cell set.
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
import tempfile
from pathlib import Path

DESIGN_DIR = Path(__file__).resolve().parent
REPO_ROOT = DESIGN_DIR.parent
NETLIST_DIR = DESIGN_DIR / "netlist"
XSCHEMRC = DESIGN_DIR / "xschemrc"

sys.path.insert(0, str(REPO_ROOT / "sim"))
from harness.pdk import PdkNotFound, find_pdk  # noqa: E402


class ExportError(RuntimeError):
    pass


def cells() -> list[str]:
    """All cells in design/, alphabetical (no hierarchy yet -- see module docstring)."""
    names = sorted(p.stem for p in DESIGN_DIR.glob("*.sch"))
    if not names:
        raise ExportError(f"no *.sch cells found under {DESIGN_DIR}")
    return names


def xschem_env() -> dict[str, str]:
    """Environment for xschem: the PDK the sim harness would use."""
    pdk = find_pdk()
    env = dict(os.environ)
    env["PDK_ROOT"] = str(pdk.path.parent)
    env["PDK"] = pdk.variant
    env["GF180_PDK_PATH"] = str(pdk.path)
    # Keep batch runs off the user's ~/.xschem state.
    env.setdefault("XSCHEM_USER_LIBRARY_PATH", str(DESIGN_DIR))
    return env


def normalize(text: str) -> str:
    """Make xschem output machine-independent (and therefore diffable)."""
    text = text.replace(str(REPO_ROOT) + os.sep, "")
    # Trailing whitespace is not load bearing and varies with symbol text.
    text = "\n".join(line.rstrip() for line in text.splitlines())
    return text.rstrip("\n") + "\n"


def export_cell(cell: str, outdir: Path, env: dict[str, str]) -> str:
    """Run xschem headless on one cell and return its normalized netlist."""
    sch = DESIGN_DIR / f"{cell}.sch"
    if not sch.is_file():
        raise ExportError(f"no such cell: {sch}")
    cmd = [
        "xschem",
        "-x",  # no X11: batch
        "-q",  # quit when done
        "-n",  # netlist
        "-s",  # spice
        "-r",  # no tclreadline (stdin/stdout may be redirected)
        "--rcfile", str(XSCHEMRC),
        "-o", str(outdir),
        str(sch),
    ]
    proc = subprocess.run(cmd, env=env, capture_output=True, text=True)
    produced = outdir / f"{cell}.spice"
    if proc.returncode != 0 or not produced.is_file():
        raise ExportError(
            f"xschem failed for {cell} (exit {proc.returncode})\n"
            f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"
        )
    text = normalize(produced.read_text())
    header = (
        f"* {cell} -- generated by design/netlist.py from design/{cell}.sch\n"
        f"* Do not edit: edit the schematic and re-run the export.\n"
    )
    return header + text


def run(check: bool, only: str | None, verbose: bool) -> int:
    try:
        env = xschem_env()
    except PdkNotFound as exc:
        print(f"design/netlist.py: {exc}", file=sys.stderr)
        return 2

    wanted = [only] if only else cells()
    netlists: dict[str, str] = {}
    with tempfile.TemporaryDirectory(prefix="gf180-netlist-") as tmp:
        outdir = Path(tmp)
        for cell in wanted:
            netlists[cell] = export_cell(cell, outdir, env)
            if verbose:
                print(f"  netlisted {cell}")

    failures: list[str] = []

    if check:
        for cell, text in netlists.items():
            committed = NETLIST_DIR / f"{cell}.spice"
            if not committed.is_file():
                failures.append(f"{committed.relative_to(REPO_ROOT)} is missing")
                continue
            have = committed.read_text()
            if have != text:
                diff = "\n".join(
                    difflib.unified_diff(
                        have.splitlines(),
                        text.splitlines(),
                        fromfile=f"committed/{cell}.spice",
                        tofile=f"regenerated/{cell}.spice",
                        lineterm="",
                    )
                )
                failures.append(
                    f"{cell}: committed netlist is stale or the export is not "
                    f"reproducible:\n{diff}"
                )
    else:
        NETLIST_DIR.mkdir(exist_ok=True)
        for cell, text in netlists.items():
            target = NETLIST_DIR / f"{cell}.spice"
            target.write_text(text)
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    status = 0
    if failures:
        print("\nFAIL:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        status = 1
    elif check:
        print(f"OK: {len(netlists)} netlist(s) reproduce byte-for-byte.")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export ngspice netlists from design/*.sch via xschem.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; verify the committed netlists are current",
    )
    parser.add_argument(
        "--cell",
        help="export a single cell",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)
    try:
        return run(check=args.check, only=args.cell, verbose=args.verbose)
    except ExportError as exc:
        print(f"design/netlist.py: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
