/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, GNU /usr/bin/c++ 13.3.0) */

module usb_bit_destuffer(clk_144, rst_144_n, enable, data_strobe, data_bit, bit_valid, out_bit, stuff_err);
  input clk_144;
  wire clk_144;
  input rst_144_n;
  wire rst_144_n;
  input enable;
  wire enable;
  input data_strobe;
  wire data_strobe;
  input data_bit;
  wire data_bit;
  output bit_valid;
  wire bit_valid;
  output out_bit;
  wire out_bit;
  output stuff_err;
  wire stuff_err;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [2:0] ones_run;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _16_ (
    .A1(ones_run[1]),
    .A2(ones_run[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _17_ (
    .A1(ones_run[0]),
    .A2(_06_),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _18_ (
    .I(data_strobe),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _19_ (
    .A1(enable),
    .A2(_07_),
    .B(_08_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_1 _20_ (
    .A1(data_strobe),
    .A2(enable),
    .A3(data_bit),
    .A4(_07_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _21_ (
    .A1(enable),
    .A2(data_bit),
    .A3(_06_),
    .Z(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _22_ (
    .A1(_08_),
    .A2(enable),
    .B(_09_),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _23_ (
    .I(ones_run[0]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _24_ (
    .A1(_08_),
    .A2(enable),
    .B(_11_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _25_ (
    .A1(ones_run[1]),
    .A2(_12_),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _26_ (
    .A1(_10_),
    .A2(_13_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _27_ (
    .I0(out_bit),
    .I1(data_bit),
    .S(_00_),
    .Z(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _28_ (
    .A1(ones_run[1]),
    .A2(_12_),
    .B(ones_run[2]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _29_ (
    .A1(_10_),
    .A2(_14_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _30_ (
    .A1(data_strobe),
    .A2(_09_),
    .B(ones_run[0]),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _31_ (
    .A1(_12_),
    .A2(_15_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _32_ (
    .CLK(clk_144),
    .D(_03_),
    .Q(out_bit),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _33_ (
    .CLK(clk_144),
    .D(_05_),
    .Q(ones_run[0]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _34_ (
    .CLK(clk_144),
    .D(_02_),
    .Q(ones_run[1]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _35_ (
    .CLK(clk_144),
    .D(_04_),
    .Q(ones_run[2]),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _36_ (
    .CLK(clk_144),
    .D(_00_),
    .Q(bit_valid),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _37_ (
    .CLK(clk_144),
    .D(_01_),
    .Q(stuff_err),
    .RN(rst_144_n)
  );
endmodule

module usb_bit_stuffer(clk, rst_n, bit_stb, bypass, sof, bit_in, bit_out, consume, stuff_pending_after);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input bit_stb;
  wire bit_stb;
  input bypass;
  wire bypass;
  input sof;
  wire sof;
  input bit_in;
  wire bit_in;
  output bit_out;
  wire bit_out;
  output consume;
  wire consume;
  output stuff_pending_after;
  wire stuff_pending_after;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] run;
  gf180mcu_fd_sc_mcu9t5v0__inv_3 _14_ (
    .I(run[0]),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_4 _15_ (
    .A1(bypass),
    .A2(sof),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_4 _16_ (
    .A1(run[1]),
    .A2(_03_),
    .A3(run[2]),
    .A4(_04_),
    .ZN(consume)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _17_ (
    .A1(bit_in),
    .A2(consume),
    .Z(bit_out)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _18_ (
    .A1(run[2]),
    .A2(bit_in),
    .A3(_04_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _19_ (
    .A1(run[1]),
    .A2(_03_),
    .A3(_05_),
    .ZN(stuff_pending_after)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _20_ (
    .A1(_03_),
    .A2(consume),
    .B(sof),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _21_ (
    .I(bypass),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _22_ (
    .A1(_07_),
    .A2(bit_in),
    .A3(bit_stb),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai22_1 _23_ (
    .A1(_03_),
    .A2(bit_stb),
    .B1(_06_),
    .B2(_08_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _24_ (
    .A1(bit_in),
    .A2(_04_),
    .A3(consume),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _25_ (
    .A1(run[0]),
    .A2(bit_stb),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_1 _26_ (
    .A1(run[1]),
    .A2(_10_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _27_ (
    .A1(bit_stb),
    .A2(_09_),
    .B(_11_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _28_ (
    .A1(run[1]),
    .A2(run[0]),
    .A3(bit_stb),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _29_ (
    .A1(run[2]),
    .A2(_12_),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _30_ (
    .A1(bit_stb),
    .A2(_09_),
    .B(_13_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _31_ (
    .CLK(clk),
    .D(_00_),
    .Q(run[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _32_ (
    .CLK(clk),
    .D(_01_),
    .Q(run[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _33_ (
    .CLK(clk),
    .D(_02_),
    .Q(run[2]),
    .RN(rst_n)
  );
endmodule

module usb_eop_detector(clk, rst_n, line_state, eop, bus_reset);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [1:0] line_state;
  wire [1:0] line_state;
  output eop;
  wire eop;
  output bus_reset;
  wire bus_reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [5:0] se0_count;
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _27_ (
    .A1(line_state[0]),
    .A2(line_state[1]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _28_ (
    .A1(rst_n),
    .A2(_08_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_4 _29_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _30_ (
    .I(se0_count[0]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _31_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(se0_count[1]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _32_ (
    .A1(_10_),
    .A2(_12_),
    .B(bus_reset),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _33_ (
    .A1(_09_),
    .A2(_13_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _34_ (
    .I(se0_count[1]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _35_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(_14_),
    .A4(_10_),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _36_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _37_ (
    .A1(_09_),
    .A2(_16_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _38_ (
    .I(se0_count[5]),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _39_ (
    .A1(_17_),
    .A2(se0_count[0]),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _40_ (
    .A1(_14_),
    .A2(_18_),
    .B(_15_),
    .C(_09_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _41_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .B(_18_),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _42_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _43_ (
    .A1(_17_),
    .A2(_20_),
    .B(se0_count[0]),
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _44_ (
    .A1(_09_),
    .A2(_19_),
    .A3(_21_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _45_ (
    .I(se0_count[4]),
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _46_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _47_ (
    .A1(_22_),
    .A2(_23_),
    .B(_09_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _48_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .Z(_24_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _49_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .B(se0_count[3]),
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _50_ (
    .A1(_09_),
    .A2(_24_),
    .A3(_25_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _51_ (
    .A1(_17_),
    .A2(_09_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _52_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .A4(_09_),
    .ZN(_26_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _53_ (
    .A1(_12_),
    .A2(_26_),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _54_ (
    .CLK(clk),
    .D(_00_),
    .Q(bus_reset)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _55_ (
    .CLK(clk),
    .D(_07_),
    .Q(eop)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _56_ (
    .CLK(clk),
    .D(_03_),
    .Q(se0_count[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _57_ (
    .CLK(clk),
    .D(_02_),
    .Q(se0_count[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _58_ (
    .CLK(clk),
    .D(_01_),
    .Q(se0_count[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _59_ (
    .CLK(clk),
    .D(_05_),
    .Q(se0_count[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _60_ (
    .CLK(clk),
    .D(_04_),
    .Q(se0_count[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _61_ (
    .CLK(clk),
    .D(_06_),
    .Q(se0_count[5])
  );
endmodule

module usb_line_state_decode(clk, rst_n, rxdp, rxdm, line_state);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  output [1:0] line_state;
  wire [1:0] line_state;
  wire _0_;
  wire _1_;
  wire _2_;
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _3_ (
    .I(rxdp),
    .ZN(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _4_ (
    .A1(_2_),
    .A2(rst_n),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _5_ (
    .A1(rst_n),
    .A2(rxdm),
    .Z(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(line_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _7_ (
    .CLK(clk),
    .D(_1_),
    .Q(line_state[1])
  );
endmodule

module usb_nrzi_decoder(clk_144, rst_144_n, bit_strobe, bit_level, bit_is_jk, data_strobe, data_bit);
  input clk_144;
  wire clk_144;
  input rst_144_n;
  wire rst_144_n;
  input bit_strobe;
  wire bit_strobe;
  input bit_level;
  wire bit_level;
  input bit_is_jk;
  wire bit_is_jk;
  output data_strobe;
  wire data_strobe;
  output data_bit;
  wire data_bit;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire prev_level;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _05_ (
    .A1(bit_strobe),
    .A2(bit_is_jk),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _06_ (
    .I(_04_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _07_ (
    .I0(bit_level),
    .I1(prev_level),
    .S(_04_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _08_ (
    .A1(bit_level),
    .A2(prev_level),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _09_ (
    .I0(_03_),
    .I1(data_bit),
    .S(_04_),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffsnq_1 _10_ (
    .CLK(clk_144),
    .D(_01_),
    .Q(prev_level),
    .SETN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _11_ (
    .CLK(clk_144),
    .D(_02_),
    .Q(data_bit),
    .RN(rst_144_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_1 _12_ (
    .CLK(clk_144),
    .D(_00_),
    .Q(data_strobe),
    .RN(rst_144_n)
  );
endmodule

module usb_nrzi_encoder(clk, rst_n, bit_stb, bypass, sof, bit_in, level_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input bit_stb;
  wire bit_stb;
  input bypass;
  wire bypass;
  input sof;
  wire sof;
  input bit_in;
  wire bit_in;
  output level_out;
  wire level_out;
  wire _0_;
  wire _1_;
  wire _2_;
  gf180mcu_fd_sc_mcu9t5v0__nor3_4 _3_ (
    .A1(bypass),
    .A2(level_out),
    .A3(sof),
    .ZN(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _4_ (
    .A1(bit_in),
    .A2(_1_),
    .Z(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _5_ (
    .I0(level_out),
    .I1(_2_),
    .S(bit_stb),
    .Z(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffsnq_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(level_out),
    .SETN(rst_n)
  );
endmodule

module usb_sync_detector(clk, rst_n, enable, data_valid, data_bit, sync_valid, sync_next);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input enable;
  wire enable;
  input data_valid;
  wire data_valid;
  input data_bit;
  wire data_bit;
  output sync_valid;
  wire sync_valid;
  output sync_next;
  wire sync_next;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [3:0] match;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _16_ (
    .I(enable),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _17_ (
    .A1(match[0]),
    .A2(match[1]),
    .A3(match[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _18_ (
    .A1(data_valid),
    .A2(data_bit),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _19_ (
    .A1(match[3]),
    .A2(_05_),
    .A3(_06_),
    .A4(_07_),
    .ZN(sync_next)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _20_ (
    .I(match[3]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _21_ (
    .A1(enable),
    .A2(rst_n),
    .A3(_07_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _22_ (
    .A1(match[0]),
    .A2(data_valid),
    .A3(match[1]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _23_ (
    .A1(match[2]),
    .A2(_10_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _24_ (
    .A1(_08_),
    .A2(_09_),
    .A3(_11_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _25_ (
    .A1(match[2]),
    .A2(_10_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _26_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _27_ (
    .A1(match[0]),
    .A2(data_valid),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _28_ (
    .A1(match[1]),
    .A2(_13_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _29_ (
    .A1(_09_),
    .A2(_10_),
    .A3(_14_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _30_ (
    .A1(match[0]),
    .A2(data_valid),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _31_ (
    .A1(_06_),
    .A2(_13_),
    .B(_15_),
    .C(_09_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _32_ (
    .A1(rst_n),
    .A2(sync_next),
    .Z(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(sync_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _34_ (
    .CLK(clk),
    .D(_03_),
    .Q(match[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _35_ (
    .CLK(clk),
    .D(_02_),
    .Q(match[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _36_ (
    .CLK(clk),
    .D(_01_),
    .Q(match[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _37_ (
    .CLK(clk),
    .D(_00_),
    .Q(match[3])
  );
endmodule

module usb_utmi_phy(clk, rst_n, TxValid, TxReady, DataOut, RxValid, RxActive, RxError, DataIn, LineState, OpMode, TermSelect, XcvrSelect, SuspendM, Reset, pu_en, trim, txdp, txdm, txoe, rxdp
, rxdm);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input TxValid;
  wire TxValid;
  output TxReady;
  wire TxReady;
  input [7:0] DataOut;
  wire [7:0] DataOut;
  output RxValid;
  wire RxValid;
  output RxActive;
  wire RxActive;
  output RxError;
  wire RxError;
  output [7:0] DataIn;
  wire [7:0] DataIn;
  output [1:0] LineState;
  wire [1:0] LineState;
  input [1:0] OpMode;
  wire [1:0] OpMode;
  input TermSelect;
  wire TermSelect;
  input XcvrSelect;
  wire XcvrSelect;
  input SuspendM;
  wire SuspendM;
  input Reset;
  wire Reset;
  output pu_en;
  wire pu_en;
  input [4:0] trim;
  wire [4:0] trim;
  output txdp;
  wire txdp;
  output txdm;
  wire txdm;
  output txoe;
  wire txoe;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire bus_reset;
  wire [2:0] byte_idx;
  wire [7:0] byte_reg;
  wire dec_data_bit;
  wire dec_data_strobe;
  wire eop_pulse;
  wire first_byte;
  wire int_rst_n;
  wire [1:0] line_state;
  wire nrzi_level;
  wire raw_mode;
  wire rx_assembly_en;
  wire rx_bit_valid;
  wire [2:0] rx_bitcnt;
  wire rx_clear;
  wire rx_dec_mask;
  wire rx_dec_strobe;
  wire rx_out_bit;
  wire rx_receiving;
  wire [7:0] rx_shift;
  wire [7:0] rx_shift_next;
  wire rx_stuff_err;
  wire stuff_bit_out;
  wire stuff_consume;
  wire stuff_pending_after;
  wire [2:0] sync_idx;
  wire sync_next;
  wire tx_clear;
  wire [2:0] tx_state;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _164_ (
    .I(rx_receiving),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_4 _165_ (
    .A1(tx_state[2]),
    .A2(tx_state[0]),
    .A3(tx_state[1]),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _166_ (
    .I(_052_),
    .ZN(txoe)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _167_ (
    .I(Reset),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _168_ (
    .A1(rst_n),
    .A2(_053_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_3 _169_ (
    .I(_054_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_2 _170_ (
    .I(_055_),
    .Z(int_rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_1 _171_ (
    .I(_054_),
    .Z(rx_clear)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _172_ (
    .A1(rx_receiving),
    .A2(_055_),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_2 _173_ (
    .I(_056_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _174_ (
    .I(dec_data_strobe),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _175_ (
    .A1(_057_),
    .A2(rx_dec_mask),
    .ZN(rx_dec_strobe)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _176_ (
    .A1(int_rst_n),
    .A2(rx_dec_strobe),
    .Z(_003_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _177_ (
    .I(line_state[0]),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _178_ (
    .A1(line_state[1]),
    .A2(_058_),
    .B(int_rst_n),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _179_ (
    .A1(line_state[1]),
    .A2(_058_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _180_ (
    .A1(_009_),
    .A2(_059_),
    .Z(_008_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _181_ (
    .I(tx_state[2]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_4 _182_ (
    .I(tx_state[0]),
    .Z(_061_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _183_ (
    .A1(_061_),
    .A2(tx_state[1]),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _184_ (
    .A1(_060_),
    .A2(_062_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _185_ (
    .A1(nrzi_level),
    .A2(_052_),
    .A3(_063_),
    .ZN(txdm)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _186_ (
    .A1(_061_),
    .A2(tx_state[1]),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _187_ (
    .A1(_063_),
    .A2(_064_),
    .B(txdm),
    .ZN(txdp)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_4 _188_ (
    .I(tx_state[1]),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _189_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(byte_idx[2]),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _190_ (
    .A1(tx_state[2]),
    .A2(_061_),
    .A3(_065_),
    .A4(_066_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _191_ (
    .A1(stuff_consume),
    .A2(_067_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _192_ (
    .A1(txoe),
    .A2(_068_),
    .ZN(TxReady)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_4 _193_ (
    .A1(tx_state[2]),
    .A2(tx_state[1]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _194_ (
    .I(TxValid),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _195_ (
    .A1(_070_),
    .A2(_052_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _196_ (
    .A1(_069_),
    .A2(_071_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _197_ (
    .A1(sync_idx[2]),
    .A2(sync_idx[0]),
    .A3(sync_idx[1]),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _198_ (
    .A1(stuff_bit_out),
    .A2(_072_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _199_ (
    .A1(_072_),
    .A2(_073_),
    .B(_074_),
    .C(int_rst_n),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _200_ (
    .A1(TxValid),
    .A2(_052_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _201_ (
    .A1(int_rst_n),
    .A2(_075_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _202_ (
    .I(OpMode[1]),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _203_ (
    .A1(_076_),
    .A2(OpMode[0]),
    .ZN(raw_mode)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _204_ (
    .A1(_060_),
    .A2(tx_state[1]),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _205_ (
    .A1(_076_),
    .A2(OpMode[0]),
    .A3(_077_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _206_ (
    .A1(tx_state[2]),
    .A2(_062_),
    .B(int_rst_n),
    .C(_075_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux4_1 _207_ (
    .I0(byte_reg[2]),
    .I1(byte_reg[3]),
    .I2(byte_reg[6]),
    .I3(byte_reg[7]),
    .S0(byte_idx[0]),
    .S1(byte_idx[2]),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _208_ (
    .I(_078_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _209_ (
    .I(byte_idx[2]),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _210_ (
    .A1(byte_reg[0]),
    .A2(_080_),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _211_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .Z(_082_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _212_ (
    .A1(byte_reg[4]),
    .A2(byte_idx[2]),
    .B(_082_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_2 _213_ (
    .I(_061_),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _214_ (
    .I(byte_reg[5]),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _215_ (
    .A1(byte_reg[1]),
    .A2(_080_),
    .B(byte_idx[1]),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _216_ (
    .A1(_085_),
    .A2(_080_),
    .B(_086_),
    .C(byte_idx[0]),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _217_ (
    .A1(_084_),
    .A2(_077_),
    .B(_087_),
    .C(_055_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi221_1 _218_ (
    .A1(byte_idx[1]),
    .A2(_079_),
    .B1(_081_),
    .B2(_083_),
    .C(_088_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _219_ (
    .A1(_060_),
    .A2(_084_),
    .A3(tx_state[1]),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _220_ (
    .A1(first_byte),
    .A2(_080_),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _221_ (
    .A1(_089_),
    .A2(_082_),
    .A3(_090_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _222_ (
    .A1(int_rst_n),
    .A2(_077_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _223_ (
    .A1(rst_n),
    .A2(TermSelect),
    .Z(pu_en)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _224_ (
    .A1(_061_),
    .A2(_069_),
    .Z(_091_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_2 _225_ (
    .A1(tx_state[2]),
    .A2(_061_),
    .A3(_065_),
    .A4(stuff_consume),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi221_2 _226_ (
    .A1(_070_),
    .A2(_067_),
    .B1(_073_),
    .B2(_091_),
    .C(_092_),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _227_ (
    .I(_064_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _228_ (
    .A1(tx_state[2]),
    .A2(_062_),
    .A3(_094_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_1 _229_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .A3(_093_),
    .A4(_095_),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_1 _230_ (
    .A1(_060_),
    .A2(_084_),
    .A3(tx_state[1]),
    .A4(_066_),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _231_ (
    .A1(_093_),
    .A2(_095_),
    .Z(_098_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi221_2 _232_ (
    .A1(_080_),
    .A2(_096_),
    .B1(_097_),
    .B2(_098_),
    .C(_054_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _233_ (
    .A1(rx_bit_valid),
    .A2(rx_assembly_en),
    .Z(_099_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _234_ (
    .A1(rx_bitcnt[0]),
    .A2(rx_bitcnt[1]),
    .A3(_099_),
    .Z(_100_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _235_ (
    .A1(rx_bitcnt[2]),
    .A2(_002_),
    .A3(_100_),
    .Z(_101_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkbuf_4 _236_ (
    .I(_101_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _237_ (
    .I0(DataIn[1]),
    .I1(rx_shift[2]),
    .S(_044_),
    .Z(_013_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai221_4 _238_ (
    .A1(stuff_consume),
    .A2(_089_),
    .B1(_067_),
    .B2(_052_),
    .C(TxValid),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_4 _239_ (
    .I(_102_),
    .Z(_103_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _240_ (
    .A1(first_byte),
    .A2(_103_),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _241_ (
    .A1(_075_),
    .A2(_104_),
    .B(rx_clear),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _242_ (
    .I0(DataIn[0]),
    .I1(rx_shift[1]),
    .S(_044_),
    .Z(_015_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _243_ (
    .I(byte_reg[7]),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _244_ (
    .A1(DataOut[7]),
    .A2(_103_),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _245_ (
    .A1(_105_),
    .A2(_103_),
    .B(_106_),
    .C(rx_clear),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _246_ (
    .A1(_061_),
    .A2(_077_),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _247_ (
    .A1(byte_idx[0]),
    .A2(byte_idx[1]),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _248_ (
    .A1(_107_),
    .A2(_108_),
    .A3(_082_),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _249_ (
    .A1(_093_),
    .A2(_095_),
    .B(byte_idx[1]),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _250_ (
    .A1(_098_),
    .A2(_109_),
    .B(_110_),
    .C(rx_clear),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _251_ (
    .A1(_107_),
    .A2(_093_),
    .B(byte_idx[0]),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _252_ (
    .A1(byte_idx[0]),
    .A2(_098_),
    .B(_111_),
    .C(rx_clear),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _253_ (
    .A1(rx_bit_valid),
    .A2(rx_assembly_en),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _254_ (
    .A1(rx_shift[4]),
    .A2(_112_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_1 _255_ (
    .I(_099_),
    .Z(_114_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _256_ (
    .A1(rx_shift[5]),
    .A2(_114_),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _257_ (
    .A1(_113_),
    .A2(_115_),
    .B(_056_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _258_ (
    .A1(rx_shift[3]),
    .A2(_112_),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _259_ (
    .A1(rx_shift[4]),
    .A2(_114_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _260_ (
    .A1(_116_),
    .A2(_117_),
    .B(_056_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _261_ (
    .A1(_004_),
    .A2(eop_pulse),
    .A3(bus_reset),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _262_ (
    .A1(sync_next),
    .A2(_118_),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _263_ (
    .A1(rx_clear),
    .A2(_119_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _264_ (
    .A1(rx_shift[2]),
    .A2(_112_),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _265_ (
    .A1(rx_shift[3]),
    .A2(_114_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _266_ (
    .A1(_120_),
    .A2(_121_),
    .B(_056_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _267_ (
    .A1(rx_shift[1]),
    .A2(_112_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _268_ (
    .A1(rx_shift[2]),
    .A2(_114_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _269_ (
    .A1(_122_),
    .A2(_123_),
    .B(_056_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _270_ (
    .A1(rx_shift[6]),
    .A2(_112_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _271_ (
    .A1(rx_shift[7]),
    .A2(_114_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _272_ (
    .A1(_124_),
    .A2(_125_),
    .B(_056_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _273_ (
    .A1(rx_bitcnt[0]),
    .A2(_114_),
    .B(rx_bitcnt[1]),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _274_ (
    .A1(_056_),
    .A2(_100_),
    .A3(_126_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _275_ (
    .A1(rx_bitcnt[0]),
    .A2(_114_),
    .B(_002_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _276_ (
    .A1(rx_bitcnt[0]),
    .A2(_114_),
    .B(_127_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _277_ (
    .A1(rx_shift[5]),
    .A2(_112_),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _278_ (
    .A1(rx_shift[6]),
    .A2(_114_),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _279_ (
    .A1(_128_),
    .A2(_129_),
    .B(_056_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _280_ (
    .A1(sync_idx[0]),
    .A2(_091_),
    .B(sync_idx[1]),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _281_ (
    .A1(sync_idx[0]),
    .A2(sync_idx[1]),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _282_ (
    .A1(_061_),
    .A2(_069_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _283_ (
    .A1(_131_),
    .A2(_132_),
    .B(_075_),
    .C(int_rst_n),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _284_ (
    .A1(_130_),
    .A2(_133_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_4 _285_ (
    .A1(sync_idx[0]),
    .A2(_091_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _286_ (
    .A1(_075_),
    .A2(_134_),
    .B(rx_clear),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _287_ (
    .A1(_073_),
    .A2(_091_),
    .B(_092_),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _288_ (
    .A1(_070_),
    .A2(_089_),
    .Z(_136_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _289_ (
    .A1(_071_),
    .A2(_097_),
    .Z(_137_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _290_ (
    .A1(_135_),
    .A2(_136_),
    .A3(_137_),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _291_ (
    .I(stuff_pending_after),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _292_ (
    .A1(tx_state[2]),
    .A2(_061_),
    .A3(_065_),
    .A4(_139_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _293_ (
    .A1(_063_),
    .A2(_064_),
    .B(_091_),
    .C(_140_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_1 _294_ (
    .A1(_135_),
    .A2(_136_),
    .A3(_137_),
    .A4(_141_),
    .Z(_142_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _295_ (
    .A1(_065_),
    .A2(_138_),
    .B(_142_),
    .C(rx_clear),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _296_ (
    .I(_056_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _297_ (
    .A1(_061_),
    .A2(_139_),
    .B(tx_state[1]),
    .C(_060_),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _298_ (
    .A1(_084_),
    .A2(int_rst_n),
    .A3(_143_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _299_ (
    .A1(int_rst_n),
    .A2(_073_),
    .A3(_091_),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _300_ (
    .A1(_138_),
    .A2(_144_),
    .B(_145_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _301_ (
    .I0(DataIn[6]),
    .I1(rx_shift[7]),
    .S(_044_),
    .Z(_033_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _302_ (
    .I0(DataIn[5]),
    .I1(rx_shift[6]),
    .S(_044_),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _303_ (
    .I0(DataIn[4]),
    .I1(rx_shift[5]),
    .S(_044_),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _304_ (
    .I0(DataIn[3]),
    .I1(rx_shift[4]),
    .S(_044_),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _305_ (
    .I0(DataIn[7]),
    .I1(rx_out_bit),
    .S(_044_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _306_ (
    .I0(DataIn[2]),
    .I1(rx_shift[3]),
    .S(_044_),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _307_ (
    .I(byte_reg[6]),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _308_ (
    .A1(DataOut[6]),
    .A2(_102_),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _309_ (
    .A1(_146_),
    .A2(_103_),
    .B(_147_),
    .C(rx_clear),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _310_ (
    .A1(rx_stuff_err),
    .A2(_002_),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _311_ (
    .A1(rx_bitcnt[2]),
    .A2(_100_),
    .B(_002_),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _312_ (
    .A1(rx_bitcnt[2]),
    .A2(_100_),
    .B(_148_),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _313_ (
    .A1(DataOut[5]),
    .A2(_102_),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _314_ (
    .A1(_085_),
    .A2(_103_),
    .B(_149_),
    .C(rx_clear),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _315_ (
    .I(byte_reg[4]),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _316_ (
    .A1(DataOut[4]),
    .A2(_102_),
    .ZN(_151_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _317_ (
    .A1(_150_),
    .A2(_103_),
    .B(_151_),
    .C(_054_),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _318_ (
    .I(byte_reg[3]),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _319_ (
    .A1(DataOut[3]),
    .A2(_102_),
    .ZN(_153_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _320_ (
    .A1(_152_),
    .A2(_103_),
    .B(_153_),
    .C(_054_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _321_ (
    .A1(rx_shift[7]),
    .A2(_112_),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _322_ (
    .A1(rx_out_bit),
    .A2(_114_),
    .ZN(_155_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _323_ (
    .A1(_154_),
    .A2(_155_),
    .B(_056_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _324_ (
    .I(byte_reg[2]),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _325_ (
    .A1(DataOut[2]),
    .A2(_102_),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _326_ (
    .A1(_156_),
    .A2(_103_),
    .B(_157_),
    .C(_054_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _327_ (
    .A1(tx_state[2]),
    .A2(_064_),
    .ZN(_158_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _328_ (
    .A1(_158_),
    .A2(_143_),
    .B(_138_),
    .C(_054_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _329_ (
    .I(byte_reg[1]),
    .ZN(_159_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _330_ (
    .A1(DataOut[1]),
    .A2(_102_),
    .ZN(_160_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _331_ (
    .A1(_159_),
    .A2(_103_),
    .B(_160_),
    .C(_054_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _332_ (
    .I(sync_idx[2]),
    .ZN(_161_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai22_1 _333_ (
    .A1(_161_),
    .A2(_133_),
    .B1(_145_),
    .B2(_131_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _334_ (
    .I(byte_reg[0]),
    .ZN(_162_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _335_ (
    .A1(DataOut[0]),
    .A2(_102_),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _336_ (
    .A1(_162_),
    .A2(_103_),
    .B(_163_),
    .C(_054_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _337_ (
    .CLK(clk),
    .D(_051_),
    .Q(byte_reg[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _338_ (
    .CLK(clk),
    .D(_049_),
    .Q(byte_reg[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _339_ (
    .CLK(clk),
    .D(_047_),
    .Q(byte_reg[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _340_ (
    .CLK(clk),
    .D(_045_),
    .Q(byte_reg[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _341_ (
    .CLK(clk),
    .D(_043_),
    .Q(byte_reg[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _342_ (
    .CLK(clk),
    .D(_042_),
    .Q(byte_reg[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _343_ (
    .CLK(clk),
    .D(_039_),
    .Q(byte_reg[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _344_ (
    .CLK(clk),
    .D(_016_),
    .Q(byte_reg[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _345_ (
    .CLK(clk),
    .D(_015_),
    .Q(DataIn[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _346_ (
    .CLK(clk),
    .D(_013_),
    .Q(DataIn[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _347_ (
    .CLK(clk),
    .D(_038_),
    .Q(DataIn[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _348_ (
    .CLK(clk),
    .D(_036_),
    .Q(DataIn[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _349_ (
    .CLK(clk),
    .D(_035_),
    .Q(DataIn[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _350_ (
    .CLK(clk),
    .D(_034_),
    .Q(DataIn[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _351_ (
    .CLK(clk),
    .D(_033_),
    .Q(DataIn[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _352_ (
    .CLK(clk),
    .D(_037_),
    .Q(DataIn[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _353_ (
    .CLK(clk),
    .D(_044_),
    .Q(RxValid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _354_ (
    .CLK(clk),
    .D(_040_),
    .Q(RxError)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _355_ (
    .CLK(clk),
    .D(_032_),
    .Q(tx_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _356_ (
    .CLK(clk),
    .D(_030_),
    .Q(tx_state[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _357_ (
    .CLK(clk),
    .D(_048_),
    .Q(tx_state[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _358_ (
    .CLK(clk),
    .D(_029_),
    .Q(sync_idx[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _359_ (
    .CLK(clk),
    .D(_028_),
    .Q(sync_idx[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _360_ (
    .CLK(clk),
    .D(_050_),
    .Q(sync_idx[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _361_ (
    .CLK(clk),
    .D(_018_),
    .Q(byte_idx[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _362_ (
    .CLK(clk),
    .D(_017_),
    .Q(byte_idx[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _363_ (
    .CLK(clk),
    .D(_012_),
    .Q(byte_idx[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _364_ (
    .CLK(clk),
    .D(_014_),
    .Q(first_byte)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _365_ (
    .CLK(clk),
    .D(_021_),
    .Q(rx_receiving)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _366_ (
    .CLK(clk),
    .D(_031_),
    .Q(rx_assembly_en)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _367_ (
    .CLK(clk),
    .D(_026_),
    .Q(rx_bitcnt[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _368_ (
    .CLK(clk),
    .D(_025_),
    .Q(rx_bitcnt[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _369_ (
    .CLK(clk),
    .D(_041_),
    .Q(rx_bitcnt[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _370_ (
    .CLK(clk),
    .D(_023_),
    .Q(rx_shift[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _371_ (
    .CLK(clk),
    .D(_022_),
    .Q(rx_shift[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _372_ (
    .CLK(clk),
    .D(_020_),
    .Q(rx_shift[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _373_ (
    .CLK(clk),
    .D(_019_),
    .Q(rx_shift[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _374_ (
    .CLK(clk),
    .D(_027_),
    .Q(rx_shift[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _375_ (
    .CLK(clk),
    .D(_024_),
    .Q(rx_shift[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _376_ (
    .CLK(clk),
    .D(_046_),
    .Q(rx_shift[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _377_ (
    .CLK(clk),
    .D(rx_clear),
    .Q(rx_dec_mask)
  );
  usb_nrzi_decoder u_decoder (
    .bit_is_jk(_008_),
    .bit_level(_009_),
    .bit_strobe(_008_),
    .clk_144(clk),
    .data_bit(dec_data_bit),
    .data_strobe(dec_data_strobe),
    .rst_144_n(rst_n)
  );
  usb_bit_destuffer u_destuffer (
    .bit_valid(rx_bit_valid),
    .clk_144(clk),
    .data_bit(dec_data_bit),
    .data_strobe(_003_),
    .enable(_002_),
    .out_bit(rx_out_bit),
    .rst_144_n(rst_n),
    .stuff_err(rx_stuff_err)
  );
  usb_nrzi_encoder u_encoder (
    .bit_in(_011_),
    .bit_stb(_006_),
    .bypass(_001_),
    .clk(clk),
    .level_out(nrzi_level),
    .rst_n(rst_n),
    .sof(_007_)
  );
  usb_eop_detector u_eop_detector (
    .bus_reset(bus_reset),
    .clk(clk),
    .eop(eop_pulse),
    .line_state(line_state),
    .rst_n(int_rst_n)
  );
  usb_line_state_decode u_line_state (
    .clk(clk),
    .line_state(line_state),
    .rst_n(int_rst_n),
    .rxdm(rxdm),
    .rxdp(rxdp)
  );
  usb_bit_stuffer u_stuffer (
    .bit_in(_010_),
    .bit_out(stuff_bit_out),
    .bit_stb(_005_),
    .bypass(raw_mode),
    .clk(clk),
    .consume(stuff_consume),
    .rst_n(rst_n),
    .sof(_000_),
    .stuff_pending_after(stuff_pending_after)
  );
  usb_sync_detector u_sync_detector (
    .clk(clk),
    .data_bit(dec_data_bit),
    .data_valid(rx_dec_strobe),
    .enable(_004_),
    .rst_n(int_rst_n),
    .sync_next(sync_next)
  );
  assign rx_shift_next = { rx_out_bit, rx_shift[7:1] };
  assign tx_clear = rx_clear;
  assign LineState = line_state;
  assign RxActive = rx_receiving;
endmodule
