/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module harness_counter(clk, rst_n, en, count);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] count;
  wire [7:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _26_ (
    .I(count[7]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _27_ (
    .I(count[5]),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _28_ (
    .I(count[6]),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _29_ (
    .I(rst_n),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _30_ (
    .A1(en),
    .A2(count[0]),
    .A3(count[1]),
    .Z(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_1 _31_ (
    .A1(en),
    .A2(count[0]),
    .A3(count[1]),
    .A4(count[2]),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _32_ (
    .A1(count[3]),
    .A2(count[4]),
    .A3(_13_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_1 _33_ (
    .A1(count[3]),
    .A2(count[4]),
    .A3(count[5]),
    .A4(_13_),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _34_ (
    .A1(_10_),
    .A2(_15_),
    .Z(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _35_ (
    .A1(_10_),
    .A2(_15_),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _36_ (
    .A1(rst_n),
    .A2(_16_),
    .A3(_17_),
    .Z(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _37_ (
    .A1(rst_n),
    .A2(_15_),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _38_ (
    .A1(_09_),
    .A2(_14_),
    .B(_18_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _39_ (
    .A1(count[3]),
    .A2(_13_),
    .B(count[4]),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _40_ (
    .A1(rst_n),
    .A2(_14_),
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _41_ (
    .A1(_19_),
    .A2(_20_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _42_ (
    .A1(count[3]),
    .A2(_13_),
    .B(rst_n),
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _43_ (
    .A1(count[3]),
    .A2(_13_),
    .B(_21_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _44_ (
    .A1(count[2]),
    .A2(_12_),
    .B(rst_n),
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _45_ (
    .A1(_13_),
    .A2(_22_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _46_ (
    .A1(en),
    .A2(count[0]),
    .B(count[1]),
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _47_ (
    .A1(_11_),
    .A2(_12_),
    .A3(_23_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _48_ (
    .A1(en),
    .A2(count[0]),
    .B(rst_n),
    .ZN(_24_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _49_ (
    .A1(en),
    .A2(count[0]),
    .B(_24_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai31_1 _50_ (
    .A1(_08_),
    .A2(_10_),
    .A3(_15_),
    .B(rst_n),
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _51_ (
    .A1(_08_),
    .A2(_16_),
    .B(_25_),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _52_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _53_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _54_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _55_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _56_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _57_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _58_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _59_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[7])
  );
endmodule
