"""Run a PVT grid through ``klt sim`` instead of hand-launching ngspice.

``run_corners.py --backend klt`` (or ``klt-local`` / ``klt-batch``) builds one
``klt sim`` corners request for the whole grid, runs it, and maps the
per-corner results back onto the harness's ``PointResult`` objects so the
usual evidence record is minted unchanged. On a shared host the full grid
must go this way: with ``KLT_SIM_BACKEND=batch`` the request is submitted to
the Spot batch fleet instead of occupying local cores.

A testbench opts in by declaring ``klt_measure`` in ``tb.json``: a map of
measurement name -> either ``{"spice": ".meas ...", "scale": k}`` (a ``.meas``
card, result multiplied by ``k`` -- the form the fleet's older runner image
accepts) or a bare *self-contained* ngspice expression string
(``measurements[].expr``, needs a newer runner). It cannot use ``derive``'s
helper vectors, because the request has no equivalent of the local deck's
free-form ``.control`` statements; put any needed reference nodes in the
testbench netlist instead. The names must equal
``measure``'s, so the same ``checks`` apply.

The supply is driven through the voltage source named by ``klt_supply_source``
(default ``vsup``), which ``klt sim`` re-targets per corner with ``alter``.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

from .corners import PvtPoint
from .pdk import Pdk
from .runner import PointResult
from .testbench import Testbench

KLT = "klt"
DEFAULT_SUPPLY_SOURCE = "vsup"


class KltError(RuntimeError):
    pass


def klt_version() -> str:
    exe = shutil.which(KLT)
    if not exe:
        raise KltError("klt not found on PATH")
    out = subprocess.run([exe, "--version"], capture_output=True, text=True, check=False)
    return (out.stdout or out.stderr).strip()


def _measurement(name: str, entry) -> dict:
    """A ``klt_measure`` entry: a ``.meas`` card dict, or a bare expression string."""
    if isinstance(entry, str):
        return {"name": name, "expr": entry}
    return {"name": name, "spice": entry["spice"]}


def _scale(manifest: dict, name: str) -> float:
    entry = manifest["klt_measure"][name]
    return float(entry.get("scale", 1.0)) if isinstance(entry, dict) else 1.0


def build_request(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    timeout_s: int,
    backend: str | None,
    manifest: dict,
    runner_version_check: str | None = None,
) -> Path:
    """Write ``body.spice`` + ``request.json`` into ``workdir``; return the request path."""
    klt_measure = manifest.get("klt_measure")
    if not klt_measure:
        raise KltError(
            f"{tb.name}: tb.json has no 'klt_measure'; add self-contained "
            "expressions to use the klt backend"
        )
    if set(klt_measure) != set(tb.measure):
        raise KltError(
            f"{tb.name}: klt_measure keys {sorted(klt_measure)} differ from "
            f"measure keys {sorted(tb.measure)}"
        )
    if len(tb.analyses) != 1:
        raise KltError(f"{tb.name}: klt backend supports exactly one analysis")
    source = manifest.get("klt_supply_source", DEFAULT_SUPPLY_SOURCE)

    workdir.mkdir(parents=True, exist_ok=True)
    body = [
        f"* {tb.name} -- circuit body for klt sim (GENERATED by sim/harness)",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={tb.nominal_supply_v!r}",
        f".param temp_c=27.0",
    ]
    for key, value in tb.params.items():
        body.append(f".param {key}={value}")
    body.append(f'.include "{pdk.design_include}"')
    if tb.dut is not None:
        body.append(f'.include "{tb.dut}"')
    body.append(f'.include "{tb.netlist}"')
    (workdir / "body.spice").write_text("\n".join(body) + "\n")

    # Process axis keeps the grid's own corner order; supply/temperature are
    # the distinct values present in the grid (full factorial by construction).
    process, seen = [], set()
    for p in points:
        if p.corner.name not in seen:
            seen.add(p.corner.name)
            process.append({"name": p.corner.name, "sections": list(p.corner.sections)})
    supplies = sorted({p.vdd for p in points})
    temps = []
    for p in points:
        if p.temp_c not in temps:
            temps.append(p.temp_c)
    if len(process) * len(supplies) * len(temps) != len(points):
        raise KltError("grid is not a full factorial; klt backend cannot express it")

    analysis = tb.analyses[0].split(None, 1)
    request = {
        "netlist": "body.spice",
        "engine": "ngspice",
        "models": {"pdk": pdk.variant, "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": process,
            "supply_v": {source: supplies},
            "temperature_c": temps,
        },
        "analysis": {"kind": analysis[0], "args": analysis[1] if len(analysis) > 1 else ""},
        "measurements": [_measurement(n, klt_measure[n]) for n in tb.measure],
        "options": {"timeout_s": timeout_s, "keep_artifacts": True},
    }
    if backend:
        request["backend"] = backend
    if runner_version_check:
        request["batch"] = {"runner_version_check": runner_version_check}
    path = workdir / "request.json"
    path.write_text(json.dumps(request, indent=2) + "\n")
    return path


def _key(process: str, temp_c: float, vdd: float) -> tuple:
    return (process, round(float(temp_c), 6), round(float(vdd), 6))


def run_grid_klt(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    manifest: dict,
    backend: str | None = None,
    runner_version_check: str | None = None,
    timeout_s: int = 300,
    on_result=None,
    log_dir: Path | None = None,
) -> tuple[list[PointResult], dict]:
    """Run the grid via ``klt sim``; return (results in grid order, backend info)."""
    request = build_request(
        tb, pdk, points, workdir, timeout_s, backend, manifest, runner_version_check
    )
    outdir = workdir / "klt-out"
    cmd = [KLT, "sim", str(request), "--format", "json", "-o", str(outdir)]
    if backend:
        cmd += ["--backend", backend]
    started = time.monotonic()
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    wall = time.monotonic() - started
    (workdir / "klt-stderr.txt").write_text(proc.stderr)
    try:
        report = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        (workdir / "klt-stdout.txt").write_text(proc.stdout)
        raise KltError(
            f"klt sim produced no JSON report (exit {proc.returncode}); "
            f"stderr tail:\n{proc.stderr[-2000:]}"
        ) from exc
    (workdir / "klt-report.json").write_text(json.dumps(report, indent=2) + "\n")

    by_key = {}
    for c in report.get("corners", []):
        vdd = next(iter(c.get("supply_v", {}).values()), None)
        by_key[_key(c.get("process"), c.get("temperature_c"), vdd)] = c

    if log_dir is not None:
        log_dir.mkdir(parents=True, exist_ok=True)
    results: list[PointResult] = []
    for point in points:
        c = by_key.get(_key(point.corner.name, point.temp_c, point.vdd))
        if c is None:
            res = PointResult(point=point, status="error", message="corner missing from klt report")
        else:
            meas = {m["name"]: m["value"] * _scale(manifest, m["name"])
                    for m in c.get("measurements", [])
                    if m.get("value") is not None and m["name"] in tb.measure}
            missing = [n for n in tb.measure if n not in meas]
            diags = "; ".join(f"{d.get('code')}: {d.get('message')}" for d in c.get("diagnostics", []))
            if c.get("status") == "error" or missing:
                res = PointResult(
                    point=point, status="failed" if meas else "error", measurements=meas,
                    missing=missing, seconds=c.get("runtime_s", 0.0),
                    message=diags or f"klt corner status {c.get('status')}",
                )
            else:
                # klt's own pass/fail grading is ignored: the harness's
                # `checks` decide, exactly as for the local backend.
                res = PointResult(point=point, status="ok", measurements=meas,
                                  seconds=c.get("runtime_s", 0.0))
            if log_dir is not None:
                log_name = f"{point.corner_id}.log"
                art = (c.get("artifacts") or {}).get("log")
                dest = log_dir / log_name
                if art and Path(art).is_file():
                    shutil.copyfile(art, dest)
                else:
                    dest.write_text(
                        f"klt sim corner {c.get('corner_id')} status={c.get('status')}\n"
                        + json.dumps(c, indent=2) + "\n"
                    )
                res.log = log_name
        results.append(res)
        if on_result is not None:
            on_result(res)

    info = {
        "backend": backend or "request-default",
        "klt_exit_code": proc.returncode,
        "klt_status": report.get("status"),
        "klt_version": (report.get("provenance") or {}).get("klt_version"),
        "engine_version": (report.get("environment") or {}).get("engine_version"),
        "remote": (report.get("environment") or {}).get("remote"),
        "wall_seconds": round(wall, 2),
    }
    return results, info
