/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module usb_bit_destuffer(clk, rst_n, init, in_valid, in_bit, out_valid, out_bit, stuff_err);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input init;
  wire init;
  input in_valid;
  wire in_valid;
  input in_bit;
  wire in_bit;
  output out_valid;
  wire out_valid;
  output out_bit;
  wire out_bit;
  output stuff_err;
  wire stuff_err;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [2:0] ones;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _22_ (
    .A1(ones[2]),
    .A2(ones[1]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_3 _23_ (
    .I(init),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_4 _24_ (
    .A1(in_bit),
    .A2(in_valid),
    .A3(_07_),
    .A4(rst_n),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _25_ (
    .A1(ones[0]),
    .A2(_06_),
    .A3(_08_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _26_ (
    .A1(_07_),
    .A2(rst_n),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_4 _27_ (
    .I(in_valid),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _28_ (
    .A1(in_bit),
    .A2(_06_),
    .B(_10_),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _29_ (
    .A1(in_valid),
    .A2(ones[0]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _30_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _31_ (
    .A1(in_valid),
    .A2(ones[0]),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _32_ (
    .A1(ones[1]),
    .A2(_13_),
    .Z(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _33_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_14_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _34_ (
    .I(ones[2]),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _35_ (
    .A1(in_valid),
    .A2(ones[1]),
    .A3(ones[0]),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _36_ (
    .A1(_15_),
    .A2(_16_),
    .B(_11_),
    .C(_09_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _37_ (
    .A1(ones[0]),
    .A2(_06_),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _38_ (
    .A1(_10_),
    .A2(_17_),
    .A3(_09_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _39_ (
    .I(out_bit),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_2 _40_ (
    .I(ones[0]),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _41_ (
    .A1(ones[2]),
    .A2(ones[1]),
    .Z(_20_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_4 _42_ (
    .A1(_19_),
    .A2(_20_),
    .B(_10_),
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai32_4 _43_ (
    .A1(_18_),
    .A2(_09_),
    .A3(_21_),
    .B1(_08_),
    .B2(_17_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _44_ (
    .CLK(clk),
    .D(_00_),
    .Q(stuff_err)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _45_ (
    .CLK(clk),
    .D(_01_),
    .Q(ones[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _46_ (
    .CLK(clk),
    .D(_02_),
    .Q(ones[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _47_ (
    .CLK(clk),
    .D(_03_),
    .Q(ones[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _48_ (
    .CLK(clk),
    .D(_05_),
    .Q(out_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _49_ (
    .CLK(clk),
    .D(_04_),
    .Q(out_valid)
  );
endmodule

module usb_bit_stuffer(clk, rst_n, init, in_valid, in_bit, in_ready, out_valid, out_bit, out_stuffed);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input init;
  wire init;
  input in_valid;
  wire in_valid;
  input in_bit;
  wire in_bit;
  output in_ready;
  wire in_ready;
  output out_valid;
  wire out_valid;
  output out_bit;
  wire out_bit;
  output out_stuffed;
  wire out_stuffed;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [2:0] ones;
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _19_ (
    .A1(ones[2]),
    .A2(ones[1]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_2 _20_ (
    .A1(ones[0]),
    .A2(_06_),
    .Z(in_ready)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _21_ (
    .A1(in_bit),
    .A2(_06_),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _22_ (
    .A1(in_valid),
    .A2(ones[0]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _23_ (
    .A1(ones[1]),
    .A2(_08_),
    .Z(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _24_ (
    .I(init),
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_2 _25_ (
    .A1(_10_),
    .A2(rst_n),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _26_ (
    .A1(in_valid),
    .A2(_07_),
    .B(_09_),
    .C(_11_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _27_ (
    .A1(in_valid),
    .A2(ones[0]),
    .A3(ones[1]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _28_ (
    .I(ones[2]),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi221_1 _29_ (
    .A1(in_valid),
    .A2(_07_),
    .B1(_12_),
    .B2(_13_),
    .C(_11_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_2 _30_ (
    .A1(ones[0]),
    .A2(_06_),
    .B(rst_n),
    .C(_10_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _31_ (
    .A1(in_valid),
    .A2(in_bit),
    .B(ones[0]),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _32_ (
    .A1(in_valid),
    .A2(ones[0]),
    .B(_14_),
    .C(_15_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _33_ (
    .A1(in_valid),
    .A2(in_bit),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _34_ (
    .I(in_valid),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _35_ (
    .A1(out_bit),
    .A2(_17_),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai22_1 _36_ (
    .A1(_14_),
    .A2(_16_),
    .B1(_18_),
    .B2(_11_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _37_ (
    .A1(_17_),
    .A2(in_ready),
    .A3(_11_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _38_ (
    .A1(_17_),
    .A2(_11_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _39_ (
    .CLK(clk),
    .D(_02_),
    .Q(ones[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _40_ (
    .CLK(clk),
    .D(_00_),
    .Q(ones[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _41_ (
    .CLK(clk),
    .D(_01_),
    .Q(ones[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _42_ (
    .CLK(clk),
    .D(_04_),
    .Q(out_stuffed)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _43_ (
    .CLK(clk),
    .D(_03_),
    .Q(out_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _44_ (
    .CLK(clk),
    .D(_05_),
    .Q(out_valid)
  );
endmodule

module usb_eop_detector(clk, rst_n, line_state, eop, bus_reset);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [1:0] line_state;
  wire [1:0] line_state;
  output eop;
  wire eop;
  output bus_reset;
  wire bus_reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [5:0] se0_count;
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _27_ (
    .A1(line_state[0]),
    .A2(line_state[1]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _28_ (
    .A1(rst_n),
    .A2(_08_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_4 _29_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _30_ (
    .I(se0_count[0]),
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _31_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(se0_count[1]),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _32_ (
    .A1(_10_),
    .A2(_12_),
    .B(bus_reset),
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _33_ (
    .A1(_09_),
    .A2(_13_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _34_ (
    .I(se0_count[1]),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _35_ (
    .A1(se0_count[5]),
    .A2(_11_),
    .A3(_14_),
    .A4(_10_),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xnor2_1 _36_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_2 _37_ (
    .A1(_09_),
    .A2(_16_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _38_ (
    .I(se0_count[5]),
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _39_ (
    .A1(_17_),
    .A2(se0_count[0]),
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _40_ (
    .A1(_14_),
    .A2(_18_),
    .B(_15_),
    .C(_09_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _41_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .B(_18_),
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _42_ (
    .A1(se0_count[1]),
    .A2(_10_),
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _43_ (
    .A1(_17_),
    .A2(_20_),
    .B(se0_count[0]),
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _44_ (
    .A1(_09_),
    .A2(_19_),
    .A3(_21_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _45_ (
    .I(se0_count[4]),
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_1 _46_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _47_ (
    .A1(_22_),
    .A2(_23_),
    .B(_09_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _48_ (
    .A1(se0_count[3]),
    .A2(se0_count[2]),
    .A3(_15_),
    .Z(_24_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _49_ (
    .A1(se0_count[2]),
    .A2(_15_),
    .B(se0_count[3]),
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _50_ (
    .A1(_09_),
    .A2(_24_),
    .A3(_25_),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _51_ (
    .A1(_17_),
    .A2(_09_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _52_ (
    .A1(se0_count[3]),
    .A2(se0_count[4]),
    .A3(se0_count[2]),
    .A4(_09_),
    .ZN(_26_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _53_ (
    .A1(_12_),
    .A2(_26_),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _54_ (
    .CLK(clk),
    .D(_00_),
    .Q(bus_reset)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _55_ (
    .CLK(clk),
    .D(_07_),
    .Q(eop)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _56_ (
    .CLK(clk),
    .D(_03_),
    .Q(se0_count[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _57_ (
    .CLK(clk),
    .D(_02_),
    .Q(se0_count[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _58_ (
    .CLK(clk),
    .D(_01_),
    .Q(se0_count[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _59_ (
    .CLK(clk),
    .D(_05_),
    .Q(se0_count[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _60_ (
    .CLK(clk),
    .D(_04_),
    .Q(se0_count[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _61_ (
    .CLK(clk),
    .D(_06_),
    .Q(se0_count[5])
  );
endmodule

module usb_line_state_decode(clk, rst_n, rxdp, rxdm, line_state);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  output [1:0] line_state;
  wire [1:0] line_state;
  wire _0_;
  wire _1_;
  wire _2_;
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _3_ (
    .I(rxdp),
    .ZN(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _4_ (
    .A1(_2_),
    .A2(rst_n),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_4 _5_ (
    .A1(rst_n),
    .A2(rxdm),
    .Z(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(line_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _7_ (
    .CLK(clk),
    .D(_1_),
    .Q(line_state[1])
  );
endmodule

module usb_nrzi_decoder(clk, rst_n, init, line_valid, line_bit, data_valid, data_bit);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input init;
  wire init;
  input line_valid;
  wire line_valid;
  input line_bit;
  wire line_bit;
  output data_valid;
  wire data_valid;
  output data_bit;
  wire data_bit;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire prev_line;
  gf180mcu_fd_sc_mcu9t5v0__xor2_2 _09_ (
    .A1(prev_line),
    .A2(line_bit),
    .Z(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _10_ (
    .I(init),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _11_ (
    .A1(line_valid),
    .A2(data_bit),
    .B(_04_),
    .C(rst_n),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _12_ (
    .A1(line_valid),
    .A2(_03_),
    .B(_05_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _13_ (
    .I(prev_line),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _14_ (
    .A1(_04_),
    .A2(rst_n),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _15_ (
    .A1(line_bit),
    .A2(line_valid),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _16_ (
    .A1(_06_),
    .A2(line_valid),
    .B(_07_),
    .C(_08_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _17_ (
    .A1(line_valid),
    .A2(_07_),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _18_ (
    .CLK(clk),
    .D(_01_),
    .Q(prev_line)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _19_ (
    .CLK(clk),
    .D(_00_),
    .Q(data_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _20_ (
    .CLK(clk),
    .D(_02_),
    .Q(data_valid)
  );
endmodule

module usb_nrzi_encoder(clk, rst_n, init, data_valid, data_bit, line_valid, line_bit);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input init;
  wire init;
  input data_valid;
  wire data_valid;
  input data_bit;
  wire data_bit;
  output line_valid;
  wire line_valid;
  output line_bit;
  wire line_bit;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  gf180mcu_fd_sc_mcu9t5v0__inv_2 _07_ (
    .I(data_valid),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _08_ (
    .A1(_05_),
    .A2(data_bit),
    .B(line_bit),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or3_4 _09_ (
    .A1(line_bit),
    .A2(_05_),
    .A3(data_bit),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _10_ (
    .I(rst_n),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _11_ (
    .A1(init),
    .A2(_03_),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _12_ (
    .A1(_06_),
    .A2(_02_),
    .A3(_04_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _13_ (
    .A1(_05_),
    .A2(init),
    .A3(_03_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _14_ (
    .CLK(clk),
    .D(_00_),
    .Q(line_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _15_ (
    .CLK(clk),
    .D(_01_),
    .Q(line_valid)
  );
endmodule

module usb_sync_detector(clk, rst_n, enable, data_valid, data_bit, sync_valid, sync_next);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input enable;
  wire enable;
  input data_valid;
  wire data_valid;
  input data_bit;
  wire data_bit;
  output sync_valid;
  wire sync_valid;
  output sync_next;
  wire sync_next;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [3:0] match;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _16_ (
    .I(enable),
    .ZN(_05_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _17_ (
    .A1(match[0]),
    .A2(match[1]),
    .A3(match[2]),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_4 _18_ (
    .A1(data_valid),
    .A2(data_bit),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_4 _19_ (
    .A1(match[3]),
    .A2(_05_),
    .A3(_06_),
    .A4(_07_),
    .ZN(sync_next)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _20_ (
    .I(match[3]),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_4 _21_ (
    .A1(enable),
    .A2(rst_n),
    .A3(_07_),
    .ZN(_09_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_2 _22_ (
    .A1(match[0]),
    .A2(data_valid),
    .A3(match[1]),
    .Z(_10_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _23_ (
    .A1(match[2]),
    .A2(_10_),
    .Z(_11_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _24_ (
    .A1(_08_),
    .A2(_09_),
    .A3(_11_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _25_ (
    .A1(match[2]),
    .A2(_10_),
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _26_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _27_ (
    .A1(match[0]),
    .A2(data_valid),
    .Z(_13_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _28_ (
    .A1(match[1]),
    .A2(_13_),
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _29_ (
    .A1(_09_),
    .A2(_10_),
    .A3(_14_),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _30_ (
    .A1(match[0]),
    .A2(data_valid),
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _31_ (
    .A1(_06_),
    .A2(_13_),
    .B(_15_),
    .C(_09_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_2 _32_ (
    .A1(rst_n),
    .A2(sync_next),
    .Z(_04_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(sync_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _34_ (
    .CLK(clk),
    .D(_03_),
    .Q(match[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _35_ (
    .CLK(clk),
    .D(_02_),
    .Q(match[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _36_ (
    .CLK(clk),
    .D(_01_),
    .Q(match[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _37_ (
    .CLK(clk),
    .D(_00_),
    .Q(match[3])
  );
endmodule

module usb_utmi_phy(clk, rst_n, TxValid, TxReady, DataOut, RxValid, RxActive, RxError, DataIn, LineState, OpMode, TermSelect, XcvrSelect, SuspendM, Reset, txdp, txdm, rxdp, rxdm);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input TxValid;
  wire TxValid;
  output TxReady;
  wire TxReady;
  input [7:0] DataOut;
  wire [7:0] DataOut;
  output RxValid;
  wire RxValid;
  output RxActive;
  wire RxActive;
  output RxError;
  wire RxError;
  output [7:0] DataIn;
  wire [7:0] DataIn;
  output [1:0] LineState;
  wire [1:0] LineState;
  input [1:0] OpMode;
  wire [1:0] OpMode;
  input TermSelect;
  wire TermSelect;
  input XcvrSelect;
  wire XcvrSelect;
  input SuspendM;
  wire SuspendM;
  input Reset;
  wire Reset;
  output txdp;
  wire txdp;
  output txdm;
  wire txdm;
  input rxdp;
  wire rxdp;
  input rxdm;
  wire rxdm;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire bus_reset;
  wire [7:0] cur_byte;
  wire dec_data_bit;
  wire dec_data_valid;
  wire dec_line_bit;
  wire dec_line_valid;
  wire destuff_in_valid;
  wire destuff_out_bit;
  wire destuff_out_valid;
  wire destuff_stuff_err;
  wire enc_line_bit;
  wire enc_line_valid;
  wire eop_pulse;
  wire int_rst_n;
  wire [1:0] line_state;
  wire [7:0] next_byte;
  wire next_valid;
  wire [2:0] rx_bitcnt;
  wire rx_receiving;
  wire [7:0] rx_shift;
  wire [7:0] rx_shift_next;
  wire stuff_in_ready;
  wire stuff_out_bit;
  wire stuff_out_valid;
  wire stuffer_in_bit;
  wire stuffer_in_valid;
  wire sync_next;
  wire [2:0] tx_bitidx;
  wire tx_init;
  wire [8:0] tx_state;
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _146_ (
    .I(rx_receiving),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_1 _147_ (
    .I(rst_n),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_2 _148_ (
    .A1(_053_),
    .A2(Reset),
    .Z(_054_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _149_ (
    .I(_054_),
    .ZN(int_rst_n)
  );
  gf180mcu_fd_sc_mcu9t5v0__and4_4 _150_ (
    .A1(tx_bitidx[0]),
    .A2(tx_bitidx[2]),
    .A3(tx_bitidx[1]),
    .A4(stuff_in_ready),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu9t5v0__inv_3 _151_ (
    .I(tx_state[3]),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_4 _152_ (
    .A1(next_valid),
    .A2(_056_),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _153_ (
    .A1(int_rst_n),
    .A2(_055_),
    .A3(_057_),
    .Z(_005_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _154_ (
    .I(tx_state[7]),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_1 _155_ (
    .I(_054_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _156_ (
    .A1(_058_),
    .A2(_059_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _157_ (
    .I(tx_state[5]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand4_1 _158_ (
    .A1(tx_bitidx[0]),
    .A2(tx_bitidx[2]),
    .A3(tx_bitidx[1]),
    .A4(stuff_in_ready),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_2 _159_ (
    .I(tx_state[3]),
    .Z(_062_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _160_ (
    .A1(next_valid),
    .A2(_061_),
    .B(_062_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _161_ (
    .A1(_060_),
    .A2(_063_),
    .B(_059_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _162_ (
    .A1(tx_state[0]),
    .A2(TxValid),
    .A3(int_rst_n),
    .Z(_003_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _163_ (
    .A1(tx_state[4]),
    .A2(int_rst_n),
    .Z(_006_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _164_ (
    .I(tx_state[0]),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _165_ (
    .A1(tx_state[1]),
    .A2(_054_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _166_ (
    .A1(_064_),
    .A2(TxValid),
    .B(_065_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _167_ (
    .A1(tx_state[2]),
    .A2(int_rst_n),
    .Z(_004_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _168_ (
    .A1(tx_state[6]),
    .A2(int_rst_n),
    .Z(_002_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _169_ (
    .A1(rx_receiving),
    .A2(dec_data_valid),
    .Z(destuff_in_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _170_ (
    .I(line_state[0]),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _171_ (
    .A1(_066_),
    .A2(line_state[1]),
    .ZN(dec_line_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor2_1 _172_ (
    .A1(line_state[0]),
    .A2(line_state[1]),
    .Z(dec_line_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _173_ (
    .A1(_062_),
    .A2(_055_),
    .B(tx_state[0]),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _174_ (
    .I(_067_),
    .ZN(TxReady)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _175_ (
    .I(cur_byte[3]),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _176_ (
    .I(cur_byte[7]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _177_ (
    .I(cur_byte[1]),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _178_ (
    .I(cur_byte[5]),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _179_ (
    .I(tx_bitidx[1]),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux4_1 _180_ (
    .I0(_068_),
    .I1(_069_),
    .I2(_070_),
    .I3(_071_),
    .S0(tx_bitidx[2]),
    .S1(_072_),
    .Z(_073_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux4_1 _181_ (
    .I0(cur_byte[0]),
    .I1(cur_byte[4]),
    .I2(cur_byte[2]),
    .I3(cur_byte[6]),
    .S0(tx_bitidx[2]),
    .S1(tx_bitidx[1]),
    .Z(_074_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _182_ (
    .A1(tx_bitidx[0]),
    .A2(_074_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_1 _183_ (
    .A1(tx_bitidx[0]),
    .A2(_073_),
    .B(_075_),
    .C(_056_),
    .ZN(stuffer_in_bit)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _184_ (
    .A1(stuff_in_ready),
    .A2(_058_),
    .B(_056_),
    .ZN(stuffer_in_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _185_ (
    .A1(tx_state[8]),
    .A2(int_rst_n),
    .Z(_000_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _186_ (
    .I0(tx_state[3]),
    .I1(TxValid),
    .S(tx_state[0]),
    .Z(_076_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_4 _187_ (
    .A1(_056_),
    .A2(_055_),
    .B(_076_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_2 _188_ (
    .A1(_057_),
    .A2(_077_),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_8 _189_ (
    .I(_077_),
    .Z(_079_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _190_ (
    .A1(next_byte[1]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_2 _191_ (
    .I(_054_),
    .Z(_081_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _192_ (
    .A1(_070_),
    .A2(_078_),
    .B(_080_),
    .C(_081_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _193_ (
    .I(cur_byte[0]),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _194_ (
    .A1(next_byte[0]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _195_ (
    .A1(_082_),
    .A2(_078_),
    .B(_083_),
    .C(_081_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _196_ (
    .A1(tx_state[3]),
    .A2(tx_state[0]),
    .B(TxValid),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_2 _197_ (
    .A1(tx_state[3]),
    .A2(_061_),
    .B(_084_),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _198_ (
    .A1(DataOut[6]),
    .A2(_085_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_1 _199_ (
    .A1(tx_state[3]),
    .A2(tx_state[0]),
    .Z(_087_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_2 _200_ (
    .A1(_056_),
    .A2(_055_),
    .B(_087_),
    .C(TxValid),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _201_ (
    .A1(next_byte[6]),
    .A2(_088_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _202_ (
    .A1(_086_),
    .A2(_089_),
    .B(_081_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _203_ (
    .A1(DataOut[5]),
    .A2(_085_),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _204_ (
    .A1(next_byte[5]),
    .A2(_088_),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _205_ (
    .A1(_090_),
    .A2(_091_),
    .B(_059_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _206_ (
    .A1(DataOut[4]),
    .A2(_085_),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _207_ (
    .A1(next_byte[4]),
    .A2(_088_),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _208_ (
    .A1(_092_),
    .A2(_093_),
    .B(_059_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _209_ (
    .A1(DataOut[3]),
    .A2(_085_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _210_ (
    .A1(next_byte[3]),
    .A2(_088_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _211_ (
    .A1(_094_),
    .A2(_095_),
    .B(_059_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _212_ (
    .A1(DataOut[2]),
    .A2(_085_),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _213_ (
    .A1(next_byte[2]),
    .A2(_088_),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _214_ (
    .A1(_096_),
    .A2(_097_),
    .B(_059_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _215_ (
    .A1(DataOut[1]),
    .A2(_085_),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _216_ (
    .A1(next_byte[1]),
    .A2(_088_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _217_ (
    .A1(_098_),
    .A2(_099_),
    .B(_081_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _218_ (
    .A1(DataOut[0]),
    .A2(_085_),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _219_ (
    .A1(next_byte[0]),
    .A2(_088_),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _220_ (
    .A1(_100_),
    .A2(_101_),
    .B(_059_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _221_ (
    .I(tx_bitidx[0]),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _222_ (
    .A1(_056_),
    .A2(stuff_in_ready),
    .B(_076_),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu9t5v0__or2_2 _223_ (
    .A1(_102_),
    .A2(_103_),
    .Z(_104_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _224_ (
    .A1(tx_bitidx[0]),
    .A2(tx_bitidx[1]),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _225_ (
    .A1(_062_),
    .A2(_105_),
    .B(_103_),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _226_ (
    .A1(_072_),
    .A2(_104_),
    .B(_106_),
    .C(_081_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _227_ (
    .I(tx_bitidx[2]),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _228_ (
    .A1(_105_),
    .A2(_103_),
    .B(_107_),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _229_ (
    .A1(int_rst_n),
    .A2(_079_),
    .A3(_108_),
    .Z(_020_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _230_ (
    .A1(_056_),
    .A2(_103_),
    .B(_102_),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _231_ (
    .A1(int_rst_n),
    .A2(_104_),
    .A3(_109_),
    .Z(_021_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and3_1 _232_ (
    .A1(rx_bitcnt[0]),
    .A2(destuff_out_valid),
    .A3(rx_bitcnt[1]),
    .Z(_110_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_2 _233_ (
    .A1(_009_),
    .A2(_053_),
    .A3(Reset),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_1 _234_ (
    .I(_111_),
    .Z(_112_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _235_ (
    .A1(rx_bitcnt[2]),
    .A2(_110_),
    .B(_112_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _236_ (
    .A1(rx_bitcnt[2]),
    .A2(_110_),
    .B(_113_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand3_2 _237_ (
    .A1(rx_bitcnt[2]),
    .A2(_110_),
    .A3(_111_),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _238_ (
    .I0(rx_shift[7]),
    .I1(DataIn[6]),
    .S(_114_),
    .Z(_023_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_2 _239_ (
    .I(destuff_out_valid),
    .Z(_115_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _240_ (
    .I0(rx_shift[7]),
    .I1(destuff_out_bit),
    .S(_115_),
    .Z(_116_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _241_ (
    .A1(_112_),
    .A2(_116_),
    .Z(_024_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _242_ (
    .I0(rx_shift[6]),
    .I1(DataIn[5]),
    .S(_114_),
    .Z(_025_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_2 _243_ (
    .A1(next_byte[7]),
    .A2(_056_),
    .A3(_057_),
    .A4(_079_),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _244_ (
    .A1(_069_),
    .A2(_078_),
    .B(_117_),
    .C(_081_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _245_ (
    .I0(rx_shift[5]),
    .I1(DataIn[4]),
    .S(_114_),
    .Z(_027_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _246_ (
    .I0(rx_shift[4]),
    .I1(DataIn[3]),
    .S(_114_),
    .Z(_028_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _247_ (
    .I0(rx_shift[3]),
    .I1(DataIn[2]),
    .S(_114_),
    .Z(_029_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _248_ (
    .I0(destuff_out_bit),
    .I1(DataIn[7]),
    .S(_114_),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _249_ (
    .I0(rx_shift[2]),
    .I1(DataIn[1]),
    .S(_114_),
    .Z(_031_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _250_ (
    .A1(tx_state[4]),
    .A2(tx_state[8]),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _251_ (
    .I(txdp),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _252_ (
    .A1(enc_line_valid),
    .A2(enc_line_bit),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _253_ (
    .A1(enc_line_valid),
    .A2(_119_),
    .B(_120_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _254_ (
    .A1(_118_),
    .A2(_121_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _255_ (
    .A1(_065_),
    .A2(_122_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _256_ (
    .I0(rx_shift[1]),
    .I1(DataIn[0]),
    .S(_114_),
    .Z(_033_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _257_ (
    .A1(DataOut[7]),
    .A2(_085_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _258_ (
    .A1(next_byte[7]),
    .A2(_088_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _259_ (
    .A1(_123_),
    .A2(_124_),
    .B(_059_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _260_ (
    .I(_114_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _261_ (
    .A1(next_valid),
    .A2(_079_),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _262_ (
    .A1(_088_),
    .A2(_125_),
    .B(_059_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _263_ (
    .I0(rx_shift[6]),
    .I1(rx_shift[7]),
    .S(_115_),
    .Z(_126_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _264_ (
    .A1(_112_),
    .A2(_126_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _265_ (
    .I0(rx_shift[5]),
    .I1(rx_shift[6]),
    .S(_115_),
    .Z(_127_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _266_ (
    .A1(_112_),
    .A2(_127_),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _267_ (
    .I0(rx_shift[4]),
    .I1(rx_shift[5]),
    .S(_115_),
    .Z(_128_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _268_ (
    .A1(_112_),
    .A2(_128_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _269_ (
    .I0(rx_shift[3]),
    .I1(rx_shift[4]),
    .S(_115_),
    .Z(_129_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _270_ (
    .A1(_112_),
    .A2(_129_),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _271_ (
    .A1(destuff_stuff_err),
    .A2(_112_),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _272_ (
    .I0(rx_shift[2]),
    .I1(rx_shift[3]),
    .S(_115_),
    .Z(_130_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _273_ (
    .A1(_112_),
    .A2(_130_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _274_ (
    .I0(rx_shift[1]),
    .I1(rx_shift[2]),
    .S(_115_),
    .Z(_131_)
  );
  gf180mcu_fd_sc_mcu9t5v0__and2_1 _275_ (
    .A1(_112_),
    .A2(_131_),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai211_1 _276_ (
    .A1(txdm),
    .A2(enc_line_valid),
    .B(_118_),
    .C(_120_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _277_ (
    .A1(tx_state[1]),
    .A2(_081_),
    .A3(_132_),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _278_ (
    .A1(rx_bitcnt[0]),
    .A2(_115_),
    .B(rx_bitcnt[1]),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor4_1 _279_ (
    .A1(_009_),
    .A2(_081_),
    .A3(_110_),
    .A4(_133_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _280_ (
    .A1(rx_bitcnt[0]),
    .A2(_115_),
    .B(_112_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi21_1 _281_ (
    .A1(rx_bitcnt[0]),
    .A2(_115_),
    .B(_134_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _282_ (
    .I(cur_byte[6]),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _283_ (
    .A1(next_byte[6]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _284_ (
    .A1(_135_),
    .A2(_078_),
    .B(_136_),
    .C(_054_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _285_ (
    .A1(next_byte[5]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _286_ (
    .A1(_071_),
    .A2(_078_),
    .B(_137_),
    .C(_081_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor3_1 _287_ (
    .A1(_009_),
    .A2(eop_pulse),
    .A3(bus_reset),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _288_ (
    .A1(sync_next),
    .A2(_138_),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _289_ (
    .A1(_059_),
    .A2(_139_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _290_ (
    .I(cur_byte[4]),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _291_ (
    .A1(next_byte[4]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _292_ (
    .A1(_140_),
    .A2(_078_),
    .B(_141_),
    .C(_054_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _293_ (
    .A1(next_byte[3]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _294_ (
    .A1(_068_),
    .A2(_078_),
    .B(_142_),
    .C(_054_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _295_ (
    .I(cur_byte[2]),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _296_ (
    .A1(next_byte[2]),
    .A2(_062_),
    .B(_057_),
    .C(_079_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu9t5v0__aoi211_2 _297_ (
    .A1(_143_),
    .A2(_078_),
    .B(_144_),
    .C(_081_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _298_ (
    .CLK(clk),
    .D(_018_),
    .Q(next_byte[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _299_ (
    .CLK(clk),
    .D(_017_),
    .Q(next_byte[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _300_ (
    .CLK(clk),
    .D(_016_),
    .Q(next_byte[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _301_ (
    .CLK(clk),
    .D(_015_),
    .Q(next_byte[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _302_ (
    .CLK(clk),
    .D(_014_),
    .Q(next_byte[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _303_ (
    .CLK(clk),
    .D(_013_),
    .Q(next_byte[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _304_ (
    .CLK(clk),
    .D(_012_),
    .Q(next_byte[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _305_ (
    .CLK(clk),
    .D(_034_),
    .Q(next_byte[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _306_ (
    .CLK(clk),
    .D(_046_),
    .Q(rx_bitcnt[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _307_ (
    .CLK(clk),
    .D(_045_),
    .Q(rx_bitcnt[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _308_ (
    .CLK(clk),
    .D(_022_),
    .Q(rx_bitcnt[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _309_ (
    .CLK(clk),
    .D(_043_),
    .Q(rx_shift[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _310_ (
    .CLK(clk),
    .D(_042_),
    .Q(rx_shift[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _311_ (
    .CLK(clk),
    .D(_040_),
    .Q(rx_shift[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _312_ (
    .CLK(clk),
    .D(_039_),
    .Q(rx_shift[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _313_ (
    .CLK(clk),
    .D(_038_),
    .Q(rx_shift[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _314_ (
    .CLK(clk),
    .D(_037_),
    .Q(rx_shift[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _315_ (
    .CLK(clk),
    .D(_024_),
    .Q(rx_shift[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _316_ (
    .CLK(clk),
    .D(_033_),
    .Q(DataIn[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _317_ (
    .CLK(clk),
    .D(_031_),
    .Q(DataIn[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _318_ (
    .CLK(clk),
    .D(_029_),
    .Q(DataIn[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _319_ (
    .CLK(clk),
    .D(_028_),
    .Q(DataIn[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _320_ (
    .CLK(clk),
    .D(_027_),
    .Q(DataIn[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _321_ (
    .CLK(clk),
    .D(_025_),
    .Q(DataIn[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _322_ (
    .CLK(clk),
    .D(_023_),
    .Q(DataIn[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _323_ (
    .CLK(clk),
    .D(_030_),
    .Q(DataIn[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _324_ (
    .CLK(clk),
    .D(_035_),
    .Q(RxValid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _325_ (
    .CLK(clk),
    .D(_041_),
    .Q(RxError)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _326_ (
    .CLK(clk),
    .D(_049_),
    .Q(rx_receiving)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _327_ (
    .CLK(clk),
    .D(_021_),
    .Q(tx_bitidx[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _328_ (
    .CLK(clk),
    .D(_019_),
    .Q(tx_bitidx[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _329_ (
    .CLK(clk),
    .D(_020_),
    .Q(tx_bitidx[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _330_ (
    .CLK(clk),
    .D(_011_),
    .Q(cur_byte[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _331_ (
    .CLK(clk),
    .D(_010_),
    .Q(cur_byte[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _332_ (
    .CLK(clk),
    .D(_052_),
    .Q(cur_byte[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _333_ (
    .CLK(clk),
    .D(_051_),
    .Q(cur_byte[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _334_ (
    .CLK(clk),
    .D(_050_),
    .Q(cur_byte[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _335_ (
    .CLK(clk),
    .D(_048_),
    .Q(cur_byte[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _336_ (
    .CLK(clk),
    .D(_047_),
    .Q(cur_byte[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _337_ (
    .CLK(clk),
    .D(_026_),
    .Q(cur_byte[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _338_ (
    .CLK(clk),
    .D(_032_),
    .Q(txdp)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _339_ (
    .CLK(clk),
    .D(_036_),
    .Q(next_valid)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _340_ (
    .CLK(clk),
    .D(_044_),
    .Q(txdm)
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _341_ (
    .CLK(clk),
    .D(_007_),
    .Q(tx_state[0])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _342_ (
    .CLK(clk),
    .D(_000_),
    .Q(tx_state[1])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _343_ (
    .CLK(clk),
    .D(_001_),
    .Q(tx_state[2])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _344_ (
    .CLK(clk),
    .D(_008_),
    .Q(tx_state[3])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _345_ (
    .CLK(clk),
    .D(_002_),
    .Q(tx_state[4])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _346_ (
    .CLK(clk),
    .D(_003_),
    .Q(tx_state[5])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _347_ (
    .CLK(clk),
    .D(_004_),
    .Q(tx_state[6])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _348_ (
    .CLK(clk),
    .D(_005_),
    .Q(tx_state[7])
  );
  gf180mcu_fd_sc_mcu9t5v0__dffq_1 _349_ (
    .CLK(clk),
    .D(_006_),
    .Q(tx_state[8])
  );
  gf180mcu_fd_sc_mcu9t5v0__tiel _350_ (
    .ZN(_145_)
  );
  usb_nrzi_decoder u_decoder (
    .clk(clk),
    .data_bit(dec_data_bit),
    .data_valid(dec_data_valid),
    .init(_145_),
    .line_bit(dec_line_bit),
    .line_valid(dec_line_valid),
    .rst_n(int_rst_n)
  );
  usb_bit_destuffer u_destuffer (
    .clk(clk),
    .in_bit(dec_data_bit),
    .in_valid(destuff_in_valid),
    .init(sync_next),
    .out_bit(destuff_out_bit),
    .out_valid(destuff_out_valid),
    .rst_n(int_rst_n),
    .stuff_err(destuff_stuff_err)
  );
  usb_nrzi_encoder u_encoder (
    .clk(clk),
    .data_bit(stuff_out_bit),
    .data_valid(stuff_out_valid),
    .init(tx_state[5]),
    .line_bit(enc_line_bit),
    .line_valid(enc_line_valid),
    .rst_n(int_rst_n)
  );
  usb_eop_detector u_eop_detector (
    .bus_reset(bus_reset),
    .clk(clk),
    .eop(eop_pulse),
    .line_state(line_state),
    .rst_n(int_rst_n)
  );
  usb_line_state_decode u_line_state (
    .clk(clk),
    .line_state(line_state),
    .rst_n(int_rst_n),
    .rxdm(rxdm),
    .rxdp(rxdp)
  );
  usb_bit_stuffer u_stuffer (
    .clk(clk),
    .in_bit(stuffer_in_bit),
    .in_ready(stuff_in_ready),
    .in_valid(stuffer_in_valid),
    .init(tx_state[5]),
    .out_bit(stuff_out_bit),
    .out_valid(stuff_out_valid),
    .rst_n(int_rst_n)
  );
  usb_sync_detector u_sync_detector (
    .clk(clk),
    .data_bit(dec_data_bit),
    .data_valid(dec_data_valid),
    .enable(_009_),
    .rst_n(int_rst_n),
    .sync_next(sync_next)
  );
  assign rx_shift_next = { destuff_out_bit, rx_shift[7:1] };
  assign tx_init = tx_state[5];
  assign LineState = line_state;
  assign RxActive = rx_receiving;
endmodule
